const flashcardData = {
  "H": {
    "name": "Hydrogen",
    "number": 1,
    "type": "Element Type 0",
    "state": "Gas",
    "mass": "1.0000 u",
    "config": "[Xe] 0s\u00b2 0p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "100 pm",
    "ionization": "5.000 eV",
    "affinity": "0.100 eV",
    "melting": "200 K",
    "boiling": "300 K",
    "density": "0.50 g/cm\u00b3",
    "discovered": "1700",
    "image": "https://images-of-elements.com/hydrogen.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Hydrogen"
  },
  "He": {
    "name": "Helium",
    "number": 2,
    "type": "Element Type 1",
    "state": "Solid",
    "mass": "2.5000 u",
    "config": "[Xe] 1s\u00b2 1p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "101 pm",
    "ionization": "5.100 eV",
    "affinity": "0.110 eV",
    "melting": "202 K",
    "boiling": "303 K",
    "density": "0.60 g/cm\u00b3",
    "discovered": "1701",
    "image": "https://images-of-elements.com/helium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Helium"
  },
  "Li": {
    "name": "Lithium",
    "number": 3,
    "type": "Element Type 2",
    "state": "Solid",
    "mass": "4.0000 u",
    "config": "[Xe] 2s\u00b2 2p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "102 pm",
    "ionization": "5.200 eV",
    "affinity": "0.120 eV",
    "melting": "204 K",
    "boiling": "306 K",
    "density": "0.70 g/cm\u00b3",
    "discovered": "1702",
    "image": "https://images-of-elements.com/lithium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Lithium"
  },
  "Be": {
    "name": "Beryllium",
    "number": 4,
    "type": "Element Type 3",
    "state": "Gas",
    "mass": "5.5000 u",
    "config": "[Xe] 3s\u00b2 3p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "103 pm",
    "ionization": "5.300 eV",
    "affinity": "0.130 eV",
    "melting": "206 K",
    "boiling": "309 K",
    "density": "0.80 g/cm\u00b3",
    "discovered": "1703",
    "image": "https://images-of-elements.com/beryllium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Beryllium"
  },
  "B": {
    "name": "Boron",
    "number": 5,
    "type": "Element Type 4",
    "state": "Solid",
    "mass": "7.0000 u",
    "config": "[Xe] 4s\u00b2 4p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "104 pm",
    "ionization": "5.400 eV",
    "affinity": "0.140 eV",
    "melting": "208 K",
    "boiling": "312 K",
    "density": "0.90 g/cm\u00b3",
    "discovered": "1704",
    "image": "https://images-of-elements.com/boron.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Boron"
  },
  "C": {
    "name": "Carbon",
    "number": 6,
    "type": "Element Type 0",
    "state": "Solid",
    "mass": "8.5000 u",
    "config": "[Xe] 5s\u00b2 5p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "105 pm",
    "ionization": "5.500 eV",
    "affinity": "0.150 eV",
    "melting": "210 K",
    "boiling": "315 K",
    "density": "1.00 g/cm\u00b3",
    "discovered": "1705",
    "image": "https://images-of-elements.com/carbon.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Carbon"
  },
  "N": {
    "name": "Nitrogen",
    "number": 7,
    "type": "Element Type 1",
    "state": "Gas",
    "mass": "10.0000 u",
    "config": "[Xe] 6s\u00b2 6p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "106 pm",
    "ionization": "5.600 eV",
    "affinity": "0.160 eV",
    "melting": "212 K",
    "boiling": "318 K",
    "density": "1.10 g/cm\u00b3",
    "discovered": "1706",
    "image": "https://images-of-elements.com/nitrogen.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Nitrogen"
  },
  "O": {
    "name": "Oxygen",
    "number": 8,
    "type": "Element Type 2",
    "state": "Solid",
    "mass": "11.5000 u",
    "config": "[Xe] 7s\u00b2 7p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "107 pm",
    "ionization": "5.700 eV",
    "affinity": "0.170 eV",
    "melting": "214 K",
    "boiling": "321 K",
    "density": "1.20 g/cm\u00b3",
    "discovered": "1707",
    "image": "https://images-of-elements.com/oxygen.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Oxygen"
  },
  "F": {
    "name": "Fluorine",
    "number": 9,
    "type": "Element Type 3",
    "state": "Solid",
    "mass": "13.0000 u",
    "config": "[Xe] 8s\u00b2 8p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "108 pm",
    "ionization": "5.800 eV",
    "affinity": "0.180 eV",
    "melting": "216 K",
    "boiling": "324 K",
    "density": "1.30 g/cm\u00b3",
    "discovered": "1708",
    "image": "https://images-of-elements.com/fluorine.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Fluorine"
  },
  "Ne": {
    "name": "Neon",
    "number": 10,
    "type": "Element Type 4",
    "state": "Gas",
    "mass": "14.5000 u",
    "config": "[Xe] 9s\u00b2 9p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "109 pm",
    "ionization": "5.900 eV",
    "affinity": "0.190 eV",
    "melting": "218 K",
    "boiling": "327 K",
    "density": "1.40 g/cm\u00b3",
    "discovered": "1709",
    "image": "https://images-of-elements.com/neon.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Neon"
  },
  "Na": {
    "name": "Sodium",
    "number": 11,
    "type": "Element Type 0",
    "state": "Solid",
    "mass": "16.0000 u",
    "config": "[Xe] 10s\u00b2 10p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "110 pm",
    "ionization": "6.000 eV",
    "affinity": "0.200 eV",
    "melting": "220 K",
    "boiling": "330 K",
    "density": "1.50 g/cm\u00b3",
    "discovered": "1710",
    "image": "https://images-of-elements.com/sodium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Sodium"
  },
  "Mg": {
    "name": "Magnesium",
    "number": 12,
    "type": "Element Type 1",
    "state": "Solid",
    "mass": "17.5000 u",
    "config": "[Xe] 11s\u00b2 11p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "111 pm",
    "ionization": "6.100 eV",
    "affinity": "0.210 eV",
    "melting": "222 K",
    "boiling": "333 K",
    "density": "1.60 g/cm\u00b3",
    "discovered": "1711",
    "image": "https://images-of-elements.com/magnesium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Magnesium"
  },
  "Al": {
    "name": "Aluminium",
    "number": 13,
    "type": "Element Type 2",
    "state": "Gas",
    "mass": "19.0000 u",
    "config": "[Xe] 12s\u00b2 12p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "112 pm",
    "ionization": "6.200 eV",
    "affinity": "0.220 eV",
    "melting": "224 K",
    "boiling": "336 K",
    "density": "1.70 g/cm\u00b3",
    "discovered": "1712",
    "image": "https://images-of-elements.com/aluminium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Aluminium"
  },
  "Si": {
    "name": "Silicon",
    "number": 14,
    "type": "Element Type 3",
    "state": "Solid",
    "mass": "20.5000 u",
    "config": "[Xe] 13s\u00b2 13p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "113 pm",
    "ionization": "6.300 eV",
    "affinity": "0.230 eV",
    "melting": "226 K",
    "boiling": "339 K",
    "density": "1.80 g/cm\u00b3",
    "discovered": "1713",
    "image": "https://images-of-elements.com/silicon.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Silicon"
  },
  "P": {
    "name": "Phosphorus",
    "number": 15,
    "type": "Element Type 4",
    "state": "Solid",
    "mass": "22.0000 u",
    "config": "[Xe] 14s\u00b2 14p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "114 pm",
    "ionization": "6.400 eV",
    "affinity": "0.240 eV",
    "melting": "228 K",
    "boiling": "342 K",
    "density": "1.90 g/cm\u00b3",
    "discovered": "1714",
    "image": "https://images-of-elements.com/phosphorus.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Phosphorus"
  },
  "S": {
    "name": "Sulfur",
    "number": 16,
    "type": "Element Type 0",
    "state": "Gas",
    "mass": "23.5000 u",
    "config": "[Xe] 15s\u00b2 15p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "115 pm",
    "ionization": "6.500 eV",
    "affinity": "0.250 eV",
    "melting": "230 K",
    "boiling": "345 K",
    "density": "2.00 g/cm\u00b3",
    "discovered": "1715",
    "image": "https://images-of-elements.com/sulfur.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Sulfur"
  },
  "Cl": {
    "name": "Chlorine",
    "number": 17,
    "type": "Element Type 1",
    "state": "Solid",
    "mass": "25.0000 u",
    "config": "[Xe] 16s\u00b2 16p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "116 pm",
    "ionization": "6.600 eV",
    "affinity": "0.260 eV",
    "melting": "232 K",
    "boiling": "348 K",
    "density": "2.10 g/cm\u00b3",
    "discovered": "1716",
    "image": "https://images-of-elements.com/chlorine.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Chlorine"
  },
  "Ar": {
    "name": "Argon",
    "number": 18,
    "type": "Element Type 2",
    "state": "Solid",
    "mass": "26.5000 u",
    "config": "[Xe] 17s\u00b2 17p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "117 pm",
    "ionization": "6.700 eV",
    "affinity": "0.270 eV",
    "melting": "234 K",
    "boiling": "351 K",
    "density": "2.20 g/cm\u00b3",
    "discovered": "1717",
    "image": "https://images-of-elements.com/argon.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Argon"
  },
  "K": {
    "name": "Potassium",
    "number": 19,
    "type": "Element Type 3",
    "state": "Gas",
    "mass": "28.0000 u",
    "config": "[Xe] 18s\u00b2 18p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "118 pm",
    "ionization": "6.800 eV",
    "affinity": "0.280 eV",
    "melting": "236 K",
    "boiling": "354 K",
    "density": "2.30 g/cm\u00b3",
    "discovered": "1718",
    "image": "https://images-of-elements.com/potassium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Potassium"
  },
  "Ca": {
    "name": "Calcium",
    "number": 20,
    "type": "Element Type 4",
    "state": "Solid",
    "mass": "29.5000 u",
    "config": "[Xe] 19s\u00b2 19p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "119 pm",
    "ionization": "6.900 eV",
    "affinity": "0.290 eV",
    "melting": "238 K",
    "boiling": "357 K",
    "density": "2.40 g/cm\u00b3",
    "discovered": "1719",
    "image": "https://images-of-elements.com/calcium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Calcium"
  },
  "Sc": {
    "name": "Scandium",
    "number": 21,
    "type": "Element Type 0",
    "state": "Solid",
    "mass": "31.0000 u",
    "config": "[Xe] 20s\u00b2 20p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "120 pm",
    "ionization": "7.000 eV",
    "affinity": "0.300 eV",
    "melting": "240 K",
    "boiling": "360 K",
    "density": "2.50 g/cm\u00b3",
    "discovered": "1720",
    "image": "https://images-of-elements.com/scandium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Scandium"
  },
  "Ti": {
    "name": "Titanium",
    "number": 22,
    "type": "Element Type 1",
    "state": "Gas",
    "mass": "32.5000 u",
    "config": "[Xe] 21s\u00b2 21p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "121 pm",
    "ionization": "7.100 eV",
    "affinity": "0.310 eV",
    "melting": "242 K",
    "boiling": "363 K",
    "density": "2.60 g/cm\u00b3",
    "discovered": "1721",
    "image": "https://images-of-elements.com/titanium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Titanium"
  },
  "V": {
    "name": "Vanadium",
    "number": 23,
    "type": "Element Type 2",
    "state": "Solid",
    "mass": "34.0000 u",
    "config": "[Xe] 22s\u00b2 22p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "122 pm",
    "ionization": "7.200 eV",
    "affinity": "0.320 eV",
    "melting": "244 K",
    "boiling": "366 K",
    "density": "2.70 g/cm\u00b3",
    "discovered": "1722",
    "image": "https://images-of-elements.com/vanadium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Vanadium"
  },
  "Cr": {
    "name": "Chromium",
    "number": 24,
    "type": "Element Type 3",
    "state": "Solid",
    "mass": "35.5000 u",
    "config": "[Xe] 23s\u00b2 23p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "123 pm",
    "ionization": "7.300 eV",
    "affinity": "0.330 eV",
    "melting": "246 K",
    "boiling": "369 K",
    "density": "2.80 g/cm\u00b3",
    "discovered": "1723",
    "image": "https://images-of-elements.com/chromium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Chromium"
  },
  "Mn": {
    "name": "Manganese",
    "number": 25,
    "type": "Element Type 4",
    "state": "Gas",
    "mass": "37.0000 u",
    "config": "[Xe] 24s\u00b2 24p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "124 pm",
    "ionization": "7.400 eV",
    "affinity": "0.340 eV",
    "melting": "248 K",
    "boiling": "372 K",
    "density": "2.90 g/cm\u00b3",
    "discovered": "1724",
    "image": "https://images-of-elements.com/manganese.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Manganese"
  },
  "Fe": {
    "name": "Iron",
    "number": 26,
    "type": "Element Type 0",
    "state": "Solid",
    "mass": "38.5000 u",
    "config": "[Xe] 25s\u00b2 25p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "125 pm",
    "ionization": "7.500 eV",
    "affinity": "0.350 eV",
    "melting": "250 K",
    "boiling": "375 K",
    "density": "3.00 g/cm\u00b3",
    "discovered": "1725",
    "image": "https://images-of-elements.com/iron.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Iron"
  },
  "Co": {
    "name": "Cobalt",
    "number": 27,
    "type": "Element Type 1",
    "state": "Solid",
    "mass": "40.0000 u",
    "config": "[Xe] 26s\u00b2 26p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "126 pm",
    "ionization": "7.600 eV",
    "affinity": "0.360 eV",
    "melting": "252 K",
    "boiling": "378 K",
    "density": "3.10 g/cm\u00b3",
    "discovered": "1726",
    "image": "https://images-of-elements.com/cobalt.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Cobalt"
  },
  "Ni": {
    "name": "Nickel",
    "number": 28,
    "type": "Element Type 2",
    "state": "Gas",
    "mass": "41.5000 u",
    "config": "[Xe] 27s\u00b2 27p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "127 pm",
    "ionization": "7.700 eV",
    "affinity": "0.370 eV",
    "melting": "254 K",
    "boiling": "381 K",
    "density": "3.20 g/cm\u00b3",
    "discovered": "1727",
    "image": "https://images-of-elements.com/nickel.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Nickel"
  },
  "Cu": {
    "name": "Copper",
    "number": 29,
    "type": "Element Type 3",
    "state": "Solid",
    "mass": "43.0000 u",
    "config": "[Xe] 28s\u00b2 28p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "128 pm",
    "ionization": "7.800 eV",
    "affinity": "0.380 eV",
    "melting": "256 K",
    "boiling": "384 K",
    "density": "3.30 g/cm\u00b3",
    "discovered": "1728",
    "image": "https://images-of-elements.com/copper.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Copper"
  },
  "Zn": {
    "name": "Zinc",
    "number": 30,
    "type": "Element Type 4",
    "state": "Solid",
    "mass": "44.5000 u",
    "config": "[Xe] 29s\u00b2 29p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "129 pm",
    "ionization": "7.900 eV",
    "affinity": "0.390 eV",
    "melting": "258 K",
    "boiling": "387 K",
    "density": "3.40 g/cm\u00b3",
    "discovered": "1729",
    "image": "https://images-of-elements.com/zinc.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Zinc"
  },
  "Ga": {
    "name": "Gallium",
    "number": 31,
    "type": "Element Type 0",
    "state": "Gas",
    "mass": "46.0000 u",
    "config": "[Xe] 30s\u00b2 30p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "130 pm",
    "ionization": "8.000 eV",
    "affinity": "0.400 eV",
    "melting": "260 K",
    "boiling": "390 K",
    "density": "3.50 g/cm\u00b3",
    "discovered": "1730",
    "image": "https://images-of-elements.com/gallium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Gallium"
  },
  "Ge": {
    "name": "Germanium",
    "number": 32,
    "type": "Element Type 1",
    "state": "Solid",
    "mass": "47.5000 u",
    "config": "[Xe] 31s\u00b2 31p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "131 pm",
    "ionization": "8.100 eV",
    "affinity": "0.410 eV",
    "melting": "262 K",
    "boiling": "393 K",
    "density": "3.60 g/cm\u00b3",
    "discovered": "1731",
    "image": "https://images-of-elements.com/germanium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Germanium"
  },
  "As": {
    "name": "Arsenic",
    "number": 33,
    "type": "Element Type 2",
    "state": "Solid",
    "mass": "49.0000 u",
    "config": "[Xe] 32s\u00b2 32p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "132 pm",
    "ionization": "8.200 eV",
    "affinity": "0.420 eV",
    "melting": "264 K",
    "boiling": "396 K",
    "density": "3.70 g/cm\u00b3",
    "discovered": "1732",
    "image": "https://images-of-elements.com/arsenic.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Arsenic"
  },
  "Se": {
    "name": "Selenium",
    "number": 34,
    "type": "Element Type 3",
    "state": "Gas",
    "mass": "50.5000 u",
    "config": "[Xe] 33s\u00b2 33p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "133 pm",
    "ionization": "8.300 eV",
    "affinity": "0.430 eV",
    "melting": "266 K",
    "boiling": "399 K",
    "density": "3.80 g/cm\u00b3",
    "discovered": "1733",
    "image": "https://images-of-elements.com/selenium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Selenium"
  },
  "Br": {
    "name": "Bromine",
    "number": 35,
    "type": "Element Type 4",
    "state": "Solid",
    "mass": "52.0000 u",
    "config": "[Xe] 34s\u00b2 34p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "134 pm",
    "ionization": "8.400 eV",
    "affinity": "0.440 eV",
    "melting": "268 K",
    "boiling": "402 K",
    "density": "3.90 g/cm\u00b3",
    "discovered": "1734",
    "image": "https://images-of-elements.com/bromine.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Bromine"
  },
  "Kr": {
    "name": "Krypton",
    "number": 36,
    "type": "Element Type 0",
    "state": "Solid",
    "mass": "53.5000 u",
    "config": "[Xe] 35s\u00b2 35p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "135 pm",
    "ionization": "8.500 eV",
    "affinity": "0.450 eV",
    "melting": "270 K",
    "boiling": "405 K",
    "density": "4.00 g/cm\u00b3",
    "discovered": "1735",
    "image": "https://images-of-elements.com/krypton.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Krypton"
  },
  "Rb": {
    "name": "Rubidium",
    "number": 37,
    "type": "Element Type 1",
    "state": "Gas",
    "mass": "55.0000 u",
    "config": "[Xe] 36s\u00b2 36p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "136 pm",
    "ionization": "8.600 eV",
    "affinity": "0.460 eV",
    "melting": "272 K",
    "boiling": "408 K",
    "density": "4.10 g/cm\u00b3",
    "discovered": "1736",
    "image": "https://images-of-elements.com/rubidium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Rubidium"
  },
  "Sr": {
    "name": "Strontium",
    "number": 38,
    "type": "Element Type 2",
    "state": "Solid",
    "mass": "56.5000 u",
    "config": "[Xe] 37s\u00b2 37p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "137 pm",
    "ionization": "8.700 eV",
    "affinity": "0.470 eV",
    "melting": "274 K",
    "boiling": "411 K",
    "density": "4.20 g/cm\u00b3",
    "discovered": "1737",
    "image": "https://images-of-elements.com/strontium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Strontium"
  },
  "Y": {
    "name": "Yttrium",
    "number": 39,
    "type": "Element Type 3",
    "state": "Solid",
    "mass": "58.0000 u",
    "config": "[Xe] 38s\u00b2 38p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "138 pm",
    "ionization": "8.800 eV",
    "affinity": "0.480 eV",
    "melting": "276 K",
    "boiling": "414 K",
    "density": "4.30 g/cm\u00b3",
    "discovered": "1738",
    "image": "https://images-of-elements.com/yttrium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Yttrium"
  },
  "Zr": {
    "name": "Zirconium",
    "number": 40,
    "type": "Element Type 4",
    "state": "Gas",
    "mass": "59.5000 u",
    "config": "[Xe] 39s\u00b2 39p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "139 pm",
    "ionization": "8.900 eV",
    "affinity": "0.490 eV",
    "melting": "278 K",
    "boiling": "417 K",
    "density": "4.40 g/cm\u00b3",
    "discovered": "1739",
    "image": "https://images-of-elements.com/zirconium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Zirconium"
  },
  "Nb": {
    "name": "Niobium",
    "number": 41,
    "type": "Element Type 0",
    "state": "Solid",
    "mass": "61.0000 u",
    "config": "[Xe] 40s\u00b2 40p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "140 pm",
    "ionization": "9.000 eV",
    "affinity": "0.500 eV",
    "melting": "280 K",
    "boiling": "420 K",
    "density": "4.50 g/cm\u00b3",
    "discovered": "1740",
    "image": "https://images-of-elements.com/niobium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Niobium"
  },
  "Mo": {
    "name": "Molybdenum",
    "number": 42,
    "type": "Element Type 1",
    "state": "Solid",
    "mass": "62.5000 u",
    "config": "[Xe] 41s\u00b2 41p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "141 pm",
    "ionization": "9.100 eV",
    "affinity": "0.510 eV",
    "melting": "282 K",
    "boiling": "423 K",
    "density": "4.60 g/cm\u00b3",
    "discovered": "1741",
    "image": "https://images-of-elements.com/molybdenum.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Molybdenum"
  },
  "Tc": {
    "name": "Technetium",
    "number": 43,
    "type": "Element Type 2",
    "state": "Gas",
    "mass": "64.0000 u",
    "config": "[Xe] 42s\u00b2 42p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "142 pm",
    "ionization": "9.200 eV",
    "affinity": "0.520 eV",
    "melting": "284 K",
    "boiling": "426 K",
    "density": "4.70 g/cm\u00b3",
    "discovered": "1742",
    "image": "https://images-of-elements.com/technetium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Technetium"
  },
  "Ru": {
    "name": "Ruthenium",
    "number": 44,
    "type": "Element Type 3",
    "state": "Solid",
    "mass": "65.5000 u",
    "config": "[Xe] 43s\u00b2 43p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "143 pm",
    "ionization": "9.300 eV",
    "affinity": "0.530 eV",
    "melting": "286 K",
    "boiling": "429 K",
    "density": "4.80 g/cm\u00b3",
    "discovered": "1743",
    "image": "https://images-of-elements.com/ruthenium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Ruthenium"
  },
  "Rh": {
    "name": "Rhodium",
    "number": 45,
    "type": "Element Type 4",
    "state": "Solid",
    "mass": "67.0000 u",
    "config": "[Xe] 44s\u00b2 44p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "144 pm",
    "ionization": "9.400 eV",
    "affinity": "0.540 eV",
    "melting": "288 K",
    "boiling": "432 K",
    "density": "4.90 g/cm\u00b3",
    "discovered": "1744",
    "image": "https://images-of-elements.com/rhodium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Rhodium"
  },
  "Pd": {
    "name": "Palladium",
    "number": 46,
    "type": "Element Type 0",
    "state": "Gas",
    "mass": "68.5000 u",
    "config": "[Xe] 45s\u00b2 45p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "145 pm",
    "ionization": "9.500 eV",
    "affinity": "0.550 eV",
    "melting": "290 K",
    "boiling": "435 K",
    "density": "5.00 g/cm\u00b3",
    "discovered": "1745",
    "image": "https://images-of-elements.com/palladium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Palladium"
  },
  "Ag": {
    "name": "Silver",
    "number": 47,
    "type": "Element Type 1",
    "state": "Solid",
    "mass": "70.0000 u",
    "config": "[Xe] 46s\u00b2 46p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "146 pm",
    "ionization": "9.600 eV",
    "affinity": "0.560 eV",
    "melting": "292 K",
    "boiling": "438 K",
    "density": "5.10 g/cm\u00b3",
    "discovered": "1746",
    "image": "https://images-of-elements.com/silver.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Silver"
  },
  "Cd": {
    "name": "Cadmium",
    "number": 48,
    "type": "Element Type 2",
    "state": "Solid",
    "mass": "71.5000 u",
    "config": "[Xe] 47s\u00b2 47p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "147 pm",
    "ionization": "9.700 eV",
    "affinity": "0.570 eV",
    "melting": "294 K",
    "boiling": "441 K",
    "density": "5.20 g/cm\u00b3",
    "discovered": "1747",
    "image": "https://images-of-elements.com/cadmium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Cadmium"
  },
  "In": {
    "name": "Indium",
    "number": 49,
    "type": "Element Type 3",
    "state": "Gas",
    "mass": "73.0000 u",
    "config": "[Xe] 48s\u00b2 48p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "148 pm",
    "ionization": "9.800 eV",
    "affinity": "0.580 eV",
    "melting": "296 K",
    "boiling": "444 K",
    "density": "5.30 g/cm\u00b3",
    "discovered": "1748",
    "image": "https://images-of-elements.com/indium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Indium"
  },
  "Sn": {
    "name": "Tin",
    "number": 50,
    "type": "Element Type 4",
    "state": "Solid",
    "mass": "74.5000 u",
    "config": "[Xe] 49s\u00b2 49p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "149 pm",
    "ionization": "9.900 eV",
    "affinity": "0.590 eV",
    "melting": "298 K",
    "boiling": "447 K",
    "density": "5.40 g/cm\u00b3",
    "discovered": "1749",
    "image": "https://images-of-elements.com/tin.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Tin"
  },
  "Sb": {
    "name": "Antimony",
    "number": 51,
    "type": "Element Type 0",
    "state": "Solid",
    "mass": "76.0000 u",
    "config": "[Xe] 50s\u00b2 50p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "150 pm",
    "ionization": "10.000 eV",
    "affinity": "0.600 eV",
    "melting": "300 K",
    "boiling": "450 K",
    "density": "5.50 g/cm\u00b3",
    "discovered": "1750",
    "image": "https://images-of-elements.com/antimony.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Antimony"
  },
  "Te": {
    "name": "Tellurium",
    "number": 52,
    "type": "Element Type 1",
    "state": "Gas",
    "mass": "77.5000 u",
    "config": "[Xe] 51s\u00b2 51p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "151 pm",
    "ionization": "10.100 eV",
    "affinity": "0.610 eV",
    "melting": "302 K",
    "boiling": "453 K",
    "density": "5.60 g/cm\u00b3",
    "discovered": "1751",
    "image": "https://images-of-elements.com/tellurium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Tellurium"
  },
  "I": {
    "name": "Iodine",
    "number": 53,
    "type": "Element Type 2",
    "state": "Solid",
    "mass": "79.0000 u",
    "config": "[Xe] 52s\u00b2 52p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "152 pm",
    "ionization": "10.200 eV",
    "affinity": "0.620 eV",
    "melting": "304 K",
    "boiling": "456 K",
    "density": "5.70 g/cm\u00b3",
    "discovered": "1752",
    "image": "https://images-of-elements.com/iodine.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Iodine"
  },
  "Xe": {
    "name": "Xenon",
    "number": 54,
    "type": "Element Type 3",
    "state": "Solid",
    "mass": "80.5000 u",
    "config": "[Xe] 53s\u00b2 53p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "153 pm",
    "ionization": "10.300 eV",
    "affinity": "0.630 eV",
    "melting": "306 K",
    "boiling": "459 K",
    "density": "5.80 g/cm\u00b3",
    "discovered": "1753",
    "image": "https://images-of-elements.com/xenon.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Xenon"
  },
  "Cs": {
    "name": "Cesium",
    "number": 55,
    "type": "Element Type 4",
    "state": "Gas",
    "mass": "82.0000 u",
    "config": "[Xe] 54s\u00b2 54p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "154 pm",
    "ionization": "10.400 eV",
    "affinity": "0.640 eV",
    "melting": "308 K",
    "boiling": "462 K",
    "density": "5.90 g/cm\u00b3",
    "discovered": "1754",
    "image": "https://images-of-elements.com/cesium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Cesium"
  },
  "Ba": {
    "name": "Barium",
    "number": 56,
    "type": "Element Type 0",
    "state": "Solid",
    "mass": "83.5000 u",
    "config": "[Xe] 55s\u00b2 55p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "155 pm",
    "ionization": "10.500 eV",
    "affinity": "0.650 eV",
    "melting": "310 K",
    "boiling": "465 K",
    "density": "6.00 g/cm\u00b3",
    "discovered": "1755",
    "image": "https://images-of-elements.com/barium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Barium"
  },
  "La": {
    "name": "Lanthanum",
    "number": 57,
    "type": "Element Type 1",
    "state": "Solid",
    "mass": "85.0000 u",
    "config": "[Xe] 56s\u00b2 56p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "156 pm",
    "ionization": "10.600 eV",
    "affinity": "0.660 eV",
    "melting": "312 K",
    "boiling": "468 K",
    "density": "6.10 g/cm\u00b3",
    "discovered": "1756",
    "image": "https://images-of-elements.com/lanthanum.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Lanthanum"
  },
  "Ce": {
    "name": "Cerium",
    "number": 58,
    "type": "Element Type 2",
    "state": "Gas",
    "mass": "86.5000 u",
    "config": "[Xe] 57s\u00b2 57p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "157 pm",
    "ionization": "10.700 eV",
    "affinity": "0.670 eV",
    "melting": "314 K",
    "boiling": "471 K",
    "density": "6.20 g/cm\u00b3",
    "discovered": "1757",
    "image": "https://images-of-elements.com/cerium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Cerium"
  },
  "Pr": {
    "name": "Praseodymium",
    "number": 59,
    "type": "Element Type 3",
    "state": "Solid",
    "mass": "88.0000 u",
    "config": "[Xe] 58s\u00b2 58p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "158 pm",
    "ionization": "10.800 eV",
    "affinity": "0.680 eV",
    "melting": "316 K",
    "boiling": "474 K",
    "density": "6.30 g/cm\u00b3",
    "discovered": "1758",
    "image": "https://images-of-elements.com/praseodymium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Praseodymium"
  },
  "Nd": {
    "name": "Neodymium",
    "number": 60,
    "type": "Element Type 4",
    "state": "Solid",
    "mass": "89.5000 u",
    "config": "[Xe] 59s\u00b2 59p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "159 pm",
    "ionization": "10.900 eV",
    "affinity": "0.690 eV",
    "melting": "318 K",
    "boiling": "477 K",
    "density": "6.40 g/cm\u00b3",
    "discovered": "1759",
    "image": "https://images-of-elements.com/neodymium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Neodymium"
  },
  "Pm": {
    "name": "Promethium",
    "number": 61,
    "type": "Element Type 0",
    "state": "Gas",
    "mass": "91.0000 u",
    "config": "[Xe] 60s\u00b2 60p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "160 pm",
    "ionization": "11.000 eV",
    "affinity": "0.700 eV",
    "melting": "320 K",
    "boiling": "480 K",
    "density": "6.50 g/cm\u00b3",
    "discovered": "1760",
    "image": "https://images-of-elements.com/promethium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Promethium"
  },
  "Sm": {
    "name": "Samarium",
    "number": 62,
    "type": "Element Type 1",
    "state": "Solid",
    "mass": "92.5000 u",
    "config": "[Xe] 61s\u00b2 61p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "161 pm",
    "ionization": "11.100 eV",
    "affinity": "0.710 eV",
    "melting": "322 K",
    "boiling": "483 K",
    "density": "6.60 g/cm\u00b3",
    "discovered": "1761",
    "image": "https://images-of-elements.com/samarium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Samarium"
  },
  "Eu": {
    "name": "Europium",
    "number": 63,
    "type": "Element Type 2",
    "state": "Solid",
    "mass": "94.0000 u",
    "config": "[Xe] 62s\u00b2 62p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "162 pm",
    "ionization": "11.200 eV",
    "affinity": "0.720 eV",
    "melting": "324 K",
    "boiling": "486 K",
    "density": "6.70 g/cm\u00b3",
    "discovered": "1762",
    "image": "https://images-of-elements.com/europium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Europium"
  },
  "Gd": {
    "name": "Gadolinium",
    "number": 64,
    "type": "Element Type 3",
    "state": "Gas",
    "mass": "95.5000 u",
    "config": "[Xe] 63s\u00b2 63p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "163 pm",
    "ionization": "11.300 eV",
    "affinity": "0.730 eV",
    "melting": "326 K",
    "boiling": "489 K",
    "density": "6.80 g/cm\u00b3",
    "discovered": "1763",
    "image": "https://images-of-elements.com/gadolinium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Gadolinium"
  },
  "Tb": {
    "name": "Terbium",
    "number": 65,
    "type": "Element Type 4",
    "state": "Solid",
    "mass": "97.0000 u",
    "config": "[Xe] 64s\u00b2 64p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "164 pm",
    "ionization": "11.400 eV",
    "affinity": "0.740 eV",
    "melting": "328 K",
    "boiling": "492 K",
    "density": "6.90 g/cm\u00b3",
    "discovered": "1764",
    "image": "https://images-of-elements.com/terbium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Terbium"
  },
  "Dy": {
    "name": "Dysprosium",
    "number": 66,
    "type": "Element Type 0",
    "state": "Solid",
    "mass": "98.5000 u",
    "config": "[Xe] 65s\u00b2 65p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "165 pm",
    "ionization": "11.500 eV",
    "affinity": "0.750 eV",
    "melting": "330 K",
    "boiling": "495 K",
    "density": "7.00 g/cm\u00b3",
    "discovered": "1765",
    "image": "https://images-of-elements.com/dysprosium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Dysprosium"
  },
  "Ho": {
    "name": "Holmium",
    "number": 67,
    "type": "Element Type 1",
    "state": "Gas",
    "mass": "100.0000 u",
    "config": "[Xe] 66s\u00b2 66p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "166 pm",
    "ionization": "11.600 eV",
    "affinity": "0.760 eV",
    "melting": "332 K",
    "boiling": "498 K",
    "density": "7.10 g/cm\u00b3",
    "discovered": "1766",
    "image": "https://images-of-elements.com/holmium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Holmium"
  },
  "Er": {
    "name": "Erbium",
    "number": 68,
    "type": "Element Type 2",
    "state": "Solid",
    "mass": "101.5000 u",
    "config": "[Xe] 67s\u00b2 67p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "167 pm",
    "ionization": "11.700 eV",
    "affinity": "0.770 eV",
    "melting": "334 K",
    "boiling": "501 K",
    "density": "7.20 g/cm\u00b3",
    "discovered": "1767",
    "image": "https://images-of-elements.com/erbium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Erbium"
  },
  "Tm": {
    "name": "Thulium",
    "number": 69,
    "type": "Element Type 3",
    "state": "Solid",
    "mass": "103.0000 u",
    "config": "[Xe] 68s\u00b2 68p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "168 pm",
    "ionization": "11.800 eV",
    "affinity": "0.780 eV",
    "melting": "336 K",
    "boiling": "504 K",
    "density": "7.30 g/cm\u00b3",
    "discovered": "1768",
    "image": "https://images-of-elements.com/thulium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Thulium"
  },
  "Yb": {
    "name": "Ytterbium",
    "number": 70,
    "type": "Element Type 4",
    "state": "Gas",
    "mass": "104.5000 u",
    "config": "[Xe] 69s\u00b2 69p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "169 pm",
    "ionization": "11.900 eV",
    "affinity": "0.790 eV",
    "melting": "338 K",
    "boiling": "507 K",
    "density": "7.40 g/cm\u00b3",
    "discovered": "1769",
    "image": "https://images-of-elements.com/ytterbium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Ytterbium"
  },
  "Lu": {
    "name": "Lutetium",
    "number": 71,
    "type": "Element Type 0",
    "state": "Solid",
    "mass": "106.0000 u",
    "config": "[Xe] 70s\u00b2 70p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "170 pm",
    "ionization": "12.000 eV",
    "affinity": "0.800 eV",
    "melting": "340 K",
    "boiling": "510 K",
    "density": "7.50 g/cm\u00b3",
    "discovered": "1770",
    "image": "https://images-of-elements.com/lutetium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Lutetium"
  },
  "Hf": {
    "name": "Hafnium",
    "number": 72,
    "type": "Element Type 1",
    "state": "Solid",
    "mass": "107.5000 u",
    "config": "[Xe] 71s\u00b2 71p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "171 pm",
    "ionization": "12.100 eV",
    "affinity": "0.810 eV",
    "melting": "342 K",
    "boiling": "513 K",
    "density": "7.60 g/cm\u00b3",
    "discovered": "1771",
    "image": "https://images-of-elements.com/hafnium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Hafnium"
  },
  "Ta": {
    "name": "Tantalum",
    "number": 73,
    "type": "Element Type 2",
    "state": "Gas",
    "mass": "109.0000 u",
    "config": "[Xe] 72s\u00b2 72p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "172 pm",
    "ionization": "12.200 eV",
    "affinity": "0.820 eV",
    "melting": "344 K",
    "boiling": "516 K",
    "density": "7.70 g/cm\u00b3",
    "discovered": "1772",
    "image": "https://images-of-elements.com/tantalum.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Tantalum"
  },
  "W": {
    "name": "Tungsten",
    "number": 74,
    "type": "Element Type 3",
    "state": "Solid",
    "mass": "110.5000 u",
    "config": "[Xe] 73s\u00b2 73p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "173 pm",
    "ionization": "12.300 eV",
    "affinity": "0.830 eV",
    "melting": "346 K",
    "boiling": "519 K",
    "density": "7.80 g/cm\u00b3",
    "discovered": "1773",
    "image": "https://images-of-elements.com/tungsten.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Tungsten"
  },
  "Re": {
    "name": "Rhenium",
    "number": 75,
    "type": "Element Type 4",
    "state": "Solid",
    "mass": "112.0000 u",
    "config": "[Xe] 74s\u00b2 74p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "174 pm",
    "ionization": "12.400 eV",
    "affinity": "0.840 eV",
    "melting": "348 K",
    "boiling": "522 K",
    "density": "7.90 g/cm\u00b3",
    "discovered": "1774",
    "image": "https://images-of-elements.com/rhenium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Rhenium"
  },
  "Os": {
    "name": "Osmium",
    "number": 76,
    "type": "Element Type 0",
    "state": "Gas",
    "mass": "113.5000 u",
    "config": "[Xe] 75s\u00b2 75p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "175 pm",
    "ionization": "12.500 eV",
    "affinity": "0.850 eV",
    "melting": "350 K",
    "boiling": "525 K",
    "density": "8.00 g/cm\u00b3",
    "discovered": "1775",
    "image": "https://images-of-elements.com/osmium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Osmium"
  },
  "Ir": {
    "name": "Iridium",
    "number": 77,
    "type": "Element Type 1",
    "state": "Solid",
    "mass": "115.0000 u",
    "config": "[Xe] 76s\u00b2 76p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "176 pm",
    "ionization": "12.600 eV",
    "affinity": "0.860 eV",
    "melting": "352 K",
    "boiling": "528 K",
    "density": "8.10 g/cm\u00b3",
    "discovered": "1776",
    "image": "https://images-of-elements.com/iridium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Iridium"
  },
  "Pt": {
    "name": "Platinum",
    "number": 78,
    "type": "Element Type 2",
    "state": "Solid",
    "mass": "116.5000 u",
    "config": "[Xe] 77s\u00b2 77p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "177 pm",
    "ionization": "12.700 eV",
    "affinity": "0.870 eV",
    "melting": "354 K",
    "boiling": "531 K",
    "density": "8.20 g/cm\u00b3",
    "discovered": "1777",
    "image": "https://images-of-elements.com/platinum.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Platinum"
  },
  "Au": {
    "name": "Gold",
    "number": 79,
    "type": "Element Type 3",
    "state": "Gas",
    "mass": "118.0000 u",
    "config": "[Xe] 78s\u00b2 78p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "178 pm",
    "ionization": "12.800 eV",
    "affinity": "0.880 eV",
    "melting": "356 K",
    "boiling": "534 K",
    "density": "8.30 g/cm\u00b3",
    "discovered": "1778",
    "image": "https://images-of-elements.com/gold.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Gold"
  },
  "Hg": {
    "name": "Mercury",
    "number": 80,
    "type": "Element Type 4",
    "state": "Solid",
    "mass": "119.5000 u",
    "config": "[Xe] 79s\u00b2 79p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "179 pm",
    "ionization": "12.900 eV",
    "affinity": "0.890 eV",
    "melting": "358 K",
    "boiling": "537 K",
    "density": "8.40 g/cm\u00b3",
    "discovered": "1779",
    "image": "https://images-of-elements.com/mercury.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Mercury"
  },
  "Tl": {
    "name": "Thallium",
    "number": 81,
    "type": "Element Type 0",
    "state": "Solid",
    "mass": "121.0000 u",
    "config": "[Xe] 80s\u00b2 80p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "180 pm",
    "ionization": "13.000 eV",
    "affinity": "0.900 eV",
    "melting": "360 K",
    "boiling": "540 K",
    "density": "8.50 g/cm\u00b3",
    "discovered": "1780",
    "image": "https://images-of-elements.com/thallium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Thallium"
  },
  "Pb": {
    "name": "Lead",
    "number": 82,
    "type": "Element Type 1",
    "state": "Gas",
    "mass": "122.5000 u",
    "config": "[Xe] 81s\u00b2 81p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "181 pm",
    "ionization": "13.100 eV",
    "affinity": "0.910 eV",
    "melting": "362 K",
    "boiling": "543 K",
    "density": "8.60 g/cm\u00b3",
    "discovered": "1781",
    "image": "https://images-of-elements.com/lead.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Lead"
  },
  "Bi": {
    "name": "Bismuth",
    "number": 83,
    "type": "Element Type 2",
    "state": "Solid",
    "mass": "124.0000 u",
    "config": "[Xe] 82s\u00b2 82p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "182 pm",
    "ionization": "13.200 eV",
    "affinity": "0.920 eV",
    "melting": "364 K",
    "boiling": "546 K",
    "density": "8.70 g/cm\u00b3",
    "discovered": "1782",
    "image": "https://images-of-elements.com/bismuth.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Bismuth"
  },
  "Po": {
    "name": "Polonium",
    "number": 84,
    "type": "Element Type 3",
    "state": "Solid",
    "mass": "125.5000 u",
    "config": "[Xe] 83s\u00b2 83p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "183 pm",
    "ionization": "13.300 eV",
    "affinity": "0.930 eV",
    "melting": "366 K",
    "boiling": "549 K",
    "density": "8.80 g/cm\u00b3",
    "discovered": "1783",
    "image": "https://images-of-elements.com/polonium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Polonium"
  },
  "At": {
    "name": "Astatine",
    "number": 85,
    "type": "Element Type 4",
    "state": "Gas",
    "mass": "127.0000 u",
    "config": "[Xe] 84s\u00b2 84p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "184 pm",
    "ionization": "13.400 eV",
    "affinity": "0.940 eV",
    "melting": "368 K",
    "boiling": "552 K",
    "density": "8.90 g/cm\u00b3",
    "discovered": "1784",
    "image": "https://images-of-elements.com/astatine.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Astatine"
  },
  "Rn": {
    "name": "Radon",
    "number": 86,
    "type": "Element Type 0",
    "state": "Solid",
    "mass": "128.5000 u",
    "config": "[Xe] 85s\u00b2 85p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "185 pm",
    "ionization": "13.500 eV",
    "affinity": "0.950 eV",
    "melting": "370 K",
    "boiling": "555 K",
    "density": "9.00 g/cm\u00b3",
    "discovered": "1785",
    "image": "https://images-of-elements.com/radon.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Radon"
  },
  "Fr": {
    "name": "Francium",
    "number": 87,
    "type": "Element Type 1",
    "state": "Solid",
    "mass": "130.0000 u",
    "config": "[Xe] 86s\u00b2 86p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "186 pm",
    "ionization": "13.600 eV",
    "affinity": "0.960 eV",
    "melting": "372 K",
    "boiling": "558 K",
    "density": "9.10 g/cm\u00b3",
    "discovered": "1786",
    "image": "https://images-of-elements.com/francium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Francium"
  },
  "Ra": {
    "name": "Radium",
    "number": 88,
    "type": "Element Type 2",
    "state": "Gas",
    "mass": "131.5000 u",
    "config": "[Xe] 87s\u00b2 87p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "187 pm",
    "ionization": "13.700 eV",
    "affinity": "0.970 eV",
    "melting": "374 K",
    "boiling": "561 K",
    "density": "9.20 g/cm\u00b3",
    "discovered": "1787",
    "image": "https://images-of-elements.com/radium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Radium"
  },
  "Ac": {
    "name": "Actinium",
    "number": 89,
    "type": "Element Type 3",
    "state": "Solid",
    "mass": "133.0000 u",
    "config": "[Xe] 88s\u00b2 88p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "188 pm",
    "ionization": "13.800 eV",
    "affinity": "0.980 eV",
    "melting": "376 K",
    "boiling": "564 K",
    "density": "9.30 g/cm\u00b3",
    "discovered": "1788",
    "image": "https://images-of-elements.com/actinium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Actinium"
  },
  "Th": {
    "name": "Thorium",
    "number": 90,
    "type": "Element Type 4",
    "state": "Solid",
    "mass": "134.5000 u",
    "config": "[Xe] 89s\u00b2 89p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "189 pm",
    "ionization": "13.900 eV",
    "affinity": "0.990 eV",
    "melting": "378 K",
    "boiling": "567 K",
    "density": "9.40 g/cm\u00b3",
    "discovered": "1789",
    "image": "https://images-of-elements.com/thorium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Thorium"
  },
  "Pa": {
    "name": "Protactinium",
    "number": 91,
    "type": "Element Type 0",
    "state": "Gas",
    "mass": "136.0000 u",
    "config": "[Xe] 90s\u00b2 90p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "190 pm",
    "ionization": "14.000 eV",
    "affinity": "1.000 eV",
    "melting": "380 K",
    "boiling": "570 K",
    "density": "9.50 g/cm\u00b3",
    "discovered": "1790",
    "image": "https://images-of-elements.com/protactinium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Protactinium"
  },
  "U": {
    "name": "Uranium",
    "number": 92,
    "type": "Element Type 1",
    "state": "Solid",
    "mass": "137.5000 u",
    "config": "[Xe] 91s\u00b2 91p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "191 pm",
    "ionization": "14.100 eV",
    "affinity": "1.010 eV",
    "melting": "382 K",
    "boiling": "573 K",
    "density": "9.60 g/cm\u00b3",
    "discovered": "1791",
    "image": "https://images-of-elements.com/uranium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Uranium"
  },
  "Np": {
    "name": "Neptunium",
    "number": 93,
    "type": "Element Type 2",
    "state": "Solid",
    "mass": "139.0000 u",
    "config": "[Xe] 92s\u00b2 92p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "192 pm",
    "ionization": "14.200 eV",
    "affinity": "1.020 eV",
    "melting": "384 K",
    "boiling": "576 K",
    "density": "9.70 g/cm\u00b3",
    "discovered": "1792",
    "image": "https://images-of-elements.com/neptunium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Neptunium"
  },
  "Pu": {
    "name": "Plutonium",
    "number": 94,
    "type": "Element Type 3",
    "state": "Gas",
    "mass": "140.5000 u",
    "config": "[Xe] 93s\u00b2 93p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "193 pm",
    "ionization": "14.300 eV",
    "affinity": "1.030 eV",
    "melting": "386 K",
    "boiling": "579 K",
    "density": "9.80 g/cm\u00b3",
    "discovered": "1793",
    "image": "https://images-of-elements.com/plutonium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Plutonium"
  },
  "Am": {
    "name": "Americium",
    "number": 95,
    "type": "Element Type 4",
    "state": "Solid",
    "mass": "142.0000 u",
    "config": "[Xe] 94s\u00b2 94p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "194 pm",
    "ionization": "14.400 eV",
    "affinity": "1.040 eV",
    "melting": "388 K",
    "boiling": "582 K",
    "density": "9.90 g/cm\u00b3",
    "discovered": "1794",
    "image": "https://images-of-elements.com/americium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Americium"
  },
  "Cm": {
    "name": "Curium",
    "number": 96,
    "type": "Element Type 0",
    "state": "Solid",
    "mass": "143.5000 u",
    "config": "[Xe] 95s\u00b2 95p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "195 pm",
    "ionization": "14.500 eV",
    "affinity": "1.050 eV",
    "melting": "390 K",
    "boiling": "585 K",
    "density": "10.00 g/cm\u00b3",
    "discovered": "1795",
    "image": "https://images-of-elements.com/curium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Curium"
  },
  "Bk": {
    "name": "Berkelium",
    "number": 97,
    "type": "Element Type 1",
    "state": "Gas",
    "mass": "145.0000 u",
    "config": "[Xe] 96s\u00b2 96p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "196 pm",
    "ionization": "14.600 eV",
    "affinity": "1.060 eV",
    "melting": "392 K",
    "boiling": "588 K",
    "density": "10.10 g/cm\u00b3",
    "discovered": "1796",
    "image": "https://images-of-elements.com/berkelium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Berkelium"
  },
  "Cf": {
    "name": "Californium",
    "number": 98,
    "type": "Element Type 2",
    "state": "Solid",
    "mass": "146.5000 u",
    "config": "[Xe] 97s\u00b2 97p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "197 pm",
    "ionization": "14.700 eV",
    "affinity": "1.070 eV",
    "melting": "394 K",
    "boiling": "591 K",
    "density": "10.20 g/cm\u00b3",
    "discovered": "1797",
    "image": "https://images-of-elements.com/californium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Californium"
  },
  "Es": {
    "name": "Einsteinium",
    "number": 99,
    "type": "Element Type 3",
    "state": "Solid",
    "mass": "148.0000 u",
    "config": "[Xe] 98s\u00b2 98p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "198 pm",
    "ionization": "14.800 eV",
    "affinity": "1.080 eV",
    "melting": "396 K",
    "boiling": "594 K",
    "density": "10.30 g/cm\u00b3",
    "discovered": "1798",
    "image": "https://images-of-elements.com/einsteinium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Einsteinium"
  },
  "Fm": {
    "name": "Fermium",
    "number": 100,
    "type": "Element Type 4",
    "state": "Gas",
    "mass": "149.5000 u",
    "config": "[Xe] 99s\u00b2 99p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "199 pm",
    "ionization": "14.900 eV",
    "affinity": "1.090 eV",
    "melting": "398 K",
    "boiling": "597 K",
    "density": "10.40 g/cm\u00b3",
    "discovered": "1799",
    "image": "https://images-of-elements.com/fermium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Fermium"
  },
  "Md": {
    "name": "Mendelevium",
    "number": 101,
    "type": "Element Type 0",
    "state": "Solid",
    "mass": "151.0000 u",
    "config": "[Xe] 100s\u00b2 100p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "200 pm",
    "ionization": "15.000 eV",
    "affinity": "1.100 eV",
    "melting": "400 K",
    "boiling": "600 K",
    "density": "10.50 g/cm\u00b3",
    "discovered": "1800",
    "image": "https://images-of-elements.com/mendelevium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Mendelevium"
  },
  "No": {
    "name": "Nobelium",
    "number": 102,
    "type": "Element Type 1",
    "state": "Solid",
    "mass": "152.5000 u",
    "config": "[Xe] 101s\u00b2 101p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "201 pm",
    "ionization": "15.100 eV",
    "affinity": "1.110 eV",
    "melting": "402 K",
    "boiling": "603 K",
    "density": "10.60 g/cm\u00b3",
    "discovered": "1801",
    "image": "https://images-of-elements.com/nobelium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Nobelium"
  },
  "Lr": {
    "name": "Lawrencium",
    "number": 103,
    "type": "Element Type 2",
    "state": "Gas",
    "mass": "154.0000 u",
    "config": "[Xe] 102s\u00b2 102p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "202 pm",
    "ionization": "15.200 eV",
    "affinity": "1.120 eV",
    "melting": "404 K",
    "boiling": "606 K",
    "density": "10.70 g/cm\u00b3",
    "discovered": "1802",
    "image": "https://images-of-elements.com/lawrencium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Lawrencium"
  },
  "Rf": {
    "name": "Rutherfordium",
    "number": 104,
    "type": "Element Type 3",
    "state": "Solid",
    "mass": "155.5000 u",
    "config": "[Xe] 103s\u00b2 103p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "203 pm",
    "ionization": "15.300 eV",
    "affinity": "1.130 eV",
    "melting": "406 K",
    "boiling": "609 K",
    "density": "10.80 g/cm\u00b3",
    "discovered": "1803",
    "image": "https://images-of-elements.com/rutherfordium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Rutherfordium"
  },
  "Db": {
    "name": "Dubnium",
    "number": 105,
    "type": "Element Type 4",
    "state": "Solid",
    "mass": "157.0000 u",
    "config": "[Xe] 104s\u00b2 104p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "204 pm",
    "ionization": "15.400 eV",
    "affinity": "1.140 eV",
    "melting": "408 K",
    "boiling": "612 K",
    "density": "10.90 g/cm\u00b3",
    "discovered": "1804",
    "image": "https://images-of-elements.com/dubnium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Dubnium"
  },
  "Sg": {
    "name": "Seaborgium",
    "number": 106,
    "type": "Element Type 0",
    "state": "Gas",
    "mass": "158.5000 u",
    "config": "[Xe] 105s\u00b2 105p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "205 pm",
    "ionization": "15.500 eV",
    "affinity": "1.150 eV",
    "melting": "410 K",
    "boiling": "615 K",
    "density": "11.00 g/cm\u00b3",
    "discovered": "1805",
    "image": "https://images-of-elements.com/seaborgium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Seaborgium"
  },
  "Bh": {
    "name": "Bohrium",
    "number": 107,
    "type": "Element Type 1",
    "state": "Solid",
    "mass": "160.0000 u",
    "config": "[Xe] 106s\u00b2 106p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "206 pm",
    "ionization": "15.600 eV",
    "affinity": "1.160 eV",
    "melting": "412 K",
    "boiling": "618 K",
    "density": "11.10 g/cm\u00b3",
    "discovered": "1806",
    "image": "https://images-of-elements.com/bohrium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Bohrium"
  },
  "Hs": {
    "name": "Hassium",
    "number": 108,
    "type": "Element Type 2",
    "state": "Solid",
    "mass": "161.5000 u",
    "config": "[Xe] 107s\u00b2 107p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "207 pm",
    "ionization": "15.700 eV",
    "affinity": "1.170 eV",
    "melting": "414 K",
    "boiling": "621 K",
    "density": "11.20 g/cm\u00b3",
    "discovered": "1807",
    "image": "https://images-of-elements.com/hassium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Hassium"
  },
  "Mt": {
    "name": "Meitnerium",
    "number": 109,
    "type": "Element Type 3",
    "state": "Gas",
    "mass": "163.0000 u",
    "config": "[Xe] 108s\u00b2 108p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "208 pm",
    "ionization": "15.800 eV",
    "affinity": "1.180 eV",
    "melting": "416 K",
    "boiling": "624 K",
    "density": "11.30 g/cm\u00b3",
    "discovered": "1808",
    "image": "https://images-of-elements.com/meitnerium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Meitnerium"
  },
  "Ds": {
    "name": "Darmstadtium",
    "number": 110,
    "type": "Element Type 4",
    "state": "Solid",
    "mass": "164.5000 u",
    "config": "[Xe] 109s\u00b2 109p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "209 pm",
    "ionization": "15.900 eV",
    "affinity": "1.190 eV",
    "melting": "418 K",
    "boiling": "627 K",
    "density": "11.40 g/cm\u00b3",
    "discovered": "1809",
    "image": "https://images-of-elements.com/darmstadtium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Darmstadtium"
  },
  "Rg": {
    "name": "Roentgenium",
    "number": 111,
    "type": "Element Type 0",
    "state": "Solid",
    "mass": "166.0000 u",
    "config": "[Xe] 110s\u00b2 110p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "210 pm",
    "ionization": "16.000 eV",
    "affinity": "1.200 eV",
    "melting": "420 K",
    "boiling": "630 K",
    "density": "11.50 g/cm\u00b3",
    "discovered": "1810",
    "image": "https://images-of-elements.com/roentgenium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Roentgenium"
  },
  "Cn": {
    "name": "Copernicium",
    "number": 112,
    "type": "Element Type 1",
    "state": "Gas",
    "mass": "167.5000 u",
    "config": "[Xe] 111s\u00b2 111p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "211 pm",
    "ionization": "16.100 eV",
    "affinity": "1.210 eV",
    "melting": "422 K",
    "boiling": "633 K",
    "density": "11.60 g/cm\u00b3",
    "discovered": "1811",
    "image": "https://images-of-elements.com/copernicium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Copernicium"
  },
  "Nh": {
    "name": "Nihonium",
    "number": 113,
    "type": "Element Type 2",
    "state": "Solid",
    "mass": "169.0000 u",
    "config": "[Xe] 112s\u00b2 112p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "212 pm",
    "ionization": "16.200 eV",
    "affinity": "1.220 eV",
    "melting": "424 K",
    "boiling": "636 K",
    "density": "11.70 g/cm\u00b3",
    "discovered": "1812",
    "image": "https://images-of-elements.com/nihonium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Nihonium"
  },
  "Fl": {
    "name": "Flerovium",
    "number": 114,
    "type": "Element Type 3",
    "state": "Solid",
    "mass": "170.5000 u",
    "config": "[Xe] 113s\u00b2 113p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "213 pm",
    "ionization": "16.300 eV",
    "affinity": "1.230 eV",
    "melting": "426 K",
    "boiling": "639 K",
    "density": "11.80 g/cm\u00b3",
    "discovered": "1813",
    "image": "https://images-of-elements.com/flerovium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Flerovium"
  },
  "Mc": {
    "name": "Moscovium",
    "number": 115,
    "type": "Element Type 4",
    "state": "Gas",
    "mass": "172.0000 u",
    "config": "[Xe] 114s\u00b2 114p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "214 pm",
    "ionization": "16.400 eV",
    "affinity": "1.240 eV",
    "melting": "428 K",
    "boiling": "642 K",
    "density": "11.90 g/cm\u00b3",
    "discovered": "1814",
    "image": "https://images-of-elements.com/moscovium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Moscovium"
  },
  "Lv": {
    "name": "Livermorium",
    "number": 116,
    "type": "Element Type 0",
    "state": "Solid",
    "mass": "173.5000 u",
    "config": "[Xe] 115s\u00b2 115p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.5",
    "radius": "215 pm",
    "ionization": "16.500 eV",
    "affinity": "1.250 eV",
    "melting": "430 K",
    "boiling": "645 K",
    "density": "12.00 g/cm\u00b3",
    "discovered": "1815",
    "image": "https://images-of-elements.com/livermorium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Livermorium"
  },
  "Ts": {
    "name": "Tennessine",
    "number": 117,
    "type": "Element Type 1",
    "state": "Solid",
    "mass": "175.0000 u",
    "config": "[Xe] 116s\u00b2 116p\u2076",
    "oxidation": "+1",
    "electronegativity": "2.0",
    "radius": "216 pm",
    "ionization": "16.600 eV",
    "affinity": "1.260 eV",
    "melting": "432 K",
    "boiling": "648 K",
    "density": "12.10 g/cm\u00b3",
    "discovered": "1816",
    "image": "https://images-of-elements.com/tennessine.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Tennessine"
  },
  "Og": {
    "name": "Oganesson",
    "number": 118,
    "type": "Element Type 2",
    "state": "Gas",
    "mass": "176.5000 u",
    "config": "[Xe] 117s\u00b2 117p\u2076",
    "oxidation": "+1",
    "electronegativity": "1.0",
    "radius": "217 pm",
    "ionization": "16.700 eV",
    "affinity": "1.270 eV",
    "melting": "434 K",
    "boiling": "651 K",
    "density": "12.20 g/cm\u00b3",
    "discovered": "1817",
    "image": "https://images-of-elements.com/oganesson.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Oganesson"
  }
};