const flashcardData = {
  "H": {
    "name": "Hydrogen",
    "number": 1,
    "type": "Nonmetal",
    "state": "Gas",
    "mass": "1.008 u",
    "config": "1s¹",
    "oxidation": "±1",
    "electronegativity": "2.20",
    "radius": "31 pm",
    "ionization": "13.595 eV",
    "affinity": "0.754 eV",
    "melting": "14.01 K",
    "boiling": "20.28 K",
    "density": "0.00008988 g/cm³",
    "discovered": "1766",
    "image": "https://images-of-elements.com/hydrogen.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Hydrogen"
  },
  "He": {
    "name": "Helium",
    "number": 2,
    "type": "Noble Gas",
    "state": "Gas",
    "mass": "4.0026 u",
    "config": "1s²",
    "oxidation": "0",
    "electronegativity": "N/A",
    "radius": "28 pm",
    "ionization": "24.587 eV",
    "affinity": "-0.22 eV",
    "melting": "N/A",
    "boiling": "4.22 K",
    "density": "0.0001785 g/cm³",
    "discovered": "1868",
    "image": "https://images-of-elements.com/helium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Helium"
  },
  "Li": {
    "name": "Lithium",
    "number": 3,
    "type": "Alkali Metal",
    "state": "Solid",
    "mass": "6.941 u",
    "config": "[He] 2s¹",
    "oxidation": "+1",
    "electronegativity": "0.98",
    "radius": "152 pm",
    "ionization": "5.392 eV",
    "affinity": "0.618 eV",
    "melting": "453.69 K",
    "boiling": "1603 K",
    "density": "0.534 g/cm³",
    "discovered": "1817",
    "image": "https://images-of-elements.com/lithium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Lithium"
  },
  "Be": {
    "name": "Beryllium",
    "number": 4,
    "type": "Alkaline Earth Metal",
    "state": "Solid",
    "mass": "9.0122 u",
    "config": "[He] 2s²",
    "oxidation": "+2",
    "electronegativity": "1.57",
    "radius": "112 pm",
    "ionization": "9.323 eV",
    "affinity": "N/A",
    "melting": "1560 K",
    "boiling": "2742 K",
    "density": "1.85 g/cm³",
    "discovered": "1798",
    "image": "https://images-of-elements.com/beryllium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Beryllium"
  },
  "B": {
    "name": "Boron",
    "number": 5,
    "type": "Metalloid",
    "state": "Solid",
    "mass": "10.81 u",
    "config": "[He] 2s² 2p¹",
    "oxidation": "+3",
    "electronegativity": "2.04",
    "radius": "85 pm",
    "ionization": "8.298 eV",
    "affinity": "0.277 eV",
    "melting": "2349 K",
    "boiling": "4200 K",
    "density": "2.46 g/cm³",
    "discovered": "1808",
    "image": "https://images-of-elements.com/boron.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Boron"
  },
  "C": {
    "name": "Carbon",
    "number": 6,
    "type": "Nonmetal",
    "state": "Solid",
    "mass": "12.011 u",
    "config": "[He] 2s² 2p²",
    "oxidation": "±4, ±2",
    "electronegativity": "2.55",
    "radius": "70 pm",
    "ionization": "11.260 eV",
    "affinity": "1.263 eV",
    "melting": "3800 K",
    "boiling": "4300 K",
    "density": "2.267 g/cm³ (graphite)",
    "discovered": "Ancient",
    "image": "https://images-of-elements.com/carbon.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Carbon"
  },
  "N": {
    "name": "Nitrogen",
    "number": 7,
    "type": "Nonmetal",
    "state": "Gas",
    "mass": "14.007 u",
    "config": "[He] 2s² 2p³",
    "oxidation": "±3, ±5",
    "electronegativity": "3.04",
    "radius": "65 pm",
    "ionization": "14.534 eV",
    "affinity": "-0.07 eV",
    "melting": "63.15 K",
    "boiling": "77.36 K",
    "density": "0.001251 g/cm³",
    "discovered": "1772",
    "image": "https://images-of-elements.com/nitrogen.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Nitrogen"
  },
  "O": {
    "name": "Oxygen",
    "number": 8,
    "type": "Nonmetal",
    "state": "Gas",
    "mass": "15.999 u",
    "config": "[He] 2s² 2p⁴",
    "oxidation": "-2",
    "electronegativity": "3.44",
    "radius": "60 pm",
    "ionization": "13.618 eV",
    "affinity": "1.461 eV",
    "melting": "54.36 K",
    "boiling": "90.20 K",
    "density": "0.001429 g/cm³",
    "discovered": "1774",
    "image": "https://images-of-elements.com/oxygen.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Oxygen"
  },
  "F": {
    "name": "Fluorine",
    "number": 9,
    "type": "Halogen",
    "state": "Gas",
    "mass": "18.998 u",
    "config": "[He] 2s² 2p⁵",
    "oxidation": "-1",
    "electronegativity": "3.98",
    "radius": "57 pm",
    "ionization": "17.423 eV",
    "affinity": "3.339 eV",
    "melting": "53.53 K",
    "boiling": "85.03 K",
    "density": "0.001696 g/cm³",
    "discovered": "1670",
    "image": "https://images-of-elements.com/fluorine.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Fluorine"
  },
  "Ne": {
    "name": "Neon",
    "number": 10,
    "type": "Noble Gas",
    "state": "Gas",
    "mass": "20.180 u",
    "config": "[He] 2s² 2p⁶",
    "oxidation": "0",
    "electronegativity": "N/A",
    "radius": "58 pm",
    "ionization": "21.565 eV",
    "affinity": "-0.30 eV",
    "melting": "24.56 K",
    "boiling": "27.07 K",
    "density": "0.0008999 g/cm³",
    "discovered": "1898",
    "image": "https://images-of-elements.com/neon.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Neon"
  },
  "Na": {
    "name": "Sodium",
    "number": 11,
    "type": "Alkali Metal",
    "state": "Solid",
    "mass": "22.990 u",
    "config": "[Ne] 3s¹",
    "oxidation": "+1",
    "electronegativity": "0.93",
    "radius": "186 pm",
    "ionization": "5.139 eV",
    "affinity": "0.548 eV",
    "melting": "370.94 K",
    "boiling": "1156 K",
    "density": "0.968 g/cm³",
    "discovered": "Ancient",
    "image": "https://images-of-elements.com/sodium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Sodium"
  },
  "Mg": {
    "name": "Magnesium",
    "number": 12,
    "type": "Alkaline Earth Metal",
    "state": "Solid",
    "mass": "24.305 u",
    "config": "[Ne] 3s²",
    "oxidation": "+2",
    "electronegativity": "1.31",
    "radius": "160 pm",
    "ionization": "7.646 eV",
    "affinity": "N/A",
    "melting": "923 K",
    "boiling": "1363 K",
    "density": "1.738 g/cm³",
    "discovered": "1808",
    "image": "https://images-of-elements.com/magnesium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Magnesium"
  },
  "Al": {
    "name": "Aluminium",
    "number": 13,
    "type": "Post-transition Metal",
    "state": "Solid",
    "mass": "26.982 u",
    "config": "[Ne] 3s² 3p¹",
    "oxidation": "+3",
    "electronegativity": "1.61",
    "radius": "143 pm",
    "ionization": "5.986 eV",
    "affinity": "0.441 eV",
    "melting": "933.47 K",
    "boiling": "2743 K",
    "density": "2.70 g/cm³",
    "discovered": "Ancient",
    "image": "https://images-of-elements.com/aluminium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Aluminium"
  },
  "Si": {
    "name": "Silicon",
    "number": 14,
    "type": "Metalloid",
    "state": "Solid",
    "mass": "28.085 u",
    "config": "[Ne] 3s² 3p²",
    "oxidation": "+4, -4",
    "electronegativity": "1.90",
    "radius": "118 pm",
    "ionization": "8.151 eV",
    "affinity": "1.385 eV",
    "melting": "1687 K",
    "boiling": "3538 K",
    "density": "2.3290 g/cm³",
    "discovered": "1823",
    "image": "https://images-of-elements.com/silicon.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Silicon"
  },
  "P": {
    "name": "Phosphorus",
    "number": 15,
    "type": "Nonmetal",
    "state": "Solid",
    "mass": "30.974 u",
    "config": "[Ne] 3s² 3p³",
    "oxidation": "±3, +5",
    "electronegativity": "2.19",
    "radius": "110 pm",
    "ionization": "10.487 eV",
    "affinity": "0.747 eV",
    "melting": "317.3 K (white)",
    "boiling": "550 K",
    "density": "1.823 g/cm³ (white)",
    "discovered": "1669",
    "image": "https://images-of-elements.com/phosphorus.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Phosphorus"
  },
  "S": {
    "name": "Sulfur",
    "number": 16,
    "type": "Nonmetal",
    "state": "Solid",
    "mass": "32.06 u",
    "config": "[Ne] 3s² 3p⁴",
    "oxidation": "-2, +4, +6",
    "electronegativity": "2.58",
    "radius": "105 pm",
    "ionization": "10.360 eV",
    "affinity": "2.077 eV",
    "melting": "388.36 K",
    "boiling": "717.8 K",
    "density": "2.07 g/cm³",
    "discovered": "Ancient",
    "image": "https://images-of-elements.com/sulfur.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Sulfur"
  },
  "Cl": {
    "name": "Chlorine",
    "number": 17,
    "type": "Halogen",
    "state": "Gas",
    "mass": "35.45 u",
    "config": "[Ne] 3s² 3p⁵",
    "oxidation": "-1, +1, +3, +5, +7",
    "electronegativity": "3.16",
    "radius": "102 pm",
    "ionization": "12.968 eV",
    "affinity": "3.617 eV",
    "melting": "171.6 K",
    "boiling": "239.11 K",
    "density": "0.003214 g/cm³",
    "discovered": "1774",
    "image": "https://images-of-elements.com/chlorine.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Chlorine"
  },
  "Ar": {
    "name": "Argon",
    "number": 18,
    "type": "Noble Gas",
    "state": "Gas",
    "mass": "39.948 u",
    "config": "[Ne] 3s² 3p⁶",
    "oxidation": "0",
    "electronegativity": "N/A",
    "radius": "106 pm",
    "ionization": "15.760 eV",
    "affinity": "-0.94 eV",
    "melting": "83.81 K",
    "boiling": "87.30 K",
    "density": "0.001784 g/cm³",
    "discovered": "1894",
    "image": "https://images-of-elements.com/argon.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Argon"
  },
  "K": {
    "name": "Potassium",
    "number": 19,
    "type": "Alkali Metal",
    "state": "Solid",
    "mass": "39.098 u",
    "config": "[Ar] 4s¹",
    "oxidation": "+1",
    "electronegativity": "0.82",
    "radius": "227 pm",
    "ionization": "4.341 eV",
    "affinity": "0.501 eV",
    "melting": "336.53 K",
    "boiling": "1032 K",
    "density": "0.856 g/cm³",
    "discovered": "1758",
    "image": "https://images-of-elements.com/potassium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Potassium"
  },
  "Ca": {
    "name": "Calcium",
    "number": 20,
    "type": "Alkaline Earth Metal",
    "state": "Solid",
    "mass": "40.078 u",
    "config": "[Ar] 4s²",
    "oxidation": "+2",
    "electronegativity": "1.00",
    "radius": "194 pm",
    "ionization": "6.113 eV",
    "affinity": "0.023 eV",
    "melting": "1115 K",
    "boiling": "1757 K",
    "density": "1.55 g/cm³",
    "discovered": "Ancient",
    "image": "https://images-of-elements.com/calcium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Calcium"
  },
  "Sc": {
    "name": "Scandium",
    "number": 21,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "44.956 u",
    "config": "[Ar] 3d¹ 4s²",
    "oxidation": "+3",
    "electronegativity": "1.36",
    "radius": "162 pm",
    "ionization": "6.54 eV",
    "affinity": "0.188 eV",
    "melting": "1814 K",
    "boiling": "3109 K",
    "density": "2.99 g/cm³",
    "discovered": "1879",
    "image": "https://images-of-elements.com/scandium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Scandium"
  },
  "Ti": {
    "name": "Titanium",
    "number": 22,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "47.867 u",
    "config": "[Ar] 3d² 4s²",
    "oxidation": "+4, +3, +2",
    "electronegativity": "1.54",
    "radius": "147 pm",
    "ionization": "6.828 eV",
    "affinity": "0.081 eV",
    "melting": "1941 K",
    "boiling": "3560 K",
    "density": "4.50 g/cm³",
    "discovered": "1791",
    "image": "https://images-of-elements.com/titanium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Titanium"
  },
  "V": {
    "name": "Vanadium",
    "number": 23,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "50.942 u",
    "config": "[Ar] 3d³ 4s²",
    "oxidation": "+5, +4, +3, +2",
    "electronegativity": "1.63",
    "radius": "134 pm",
    "ionization": "6.746 eV",
    "affinity": "0.525 eV",
    "melting": "2183 K",
    "boiling": "3680 K",
    "density": "6.11 g/cm³",
    "discovered": "1801",
    "image": "https://images-of-elements.com/vanadium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Vanadium"
  },
  "Cr": {
    "name": "Chromium",
    "number": 24,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "51.996 u",
    "config": "[Ar] 3d⁵ 4s¹",
    "oxidation": "+6, +3, +2",
    "electronegativity": "1.66",
    "radius": "128 pm",
    "ionization": "6.766 eV",
    "affinity": "0.666 eV",
    "melting": "2180 K",
    "boiling": "2944 K",
    "density": "7.15 g/cm³",
    "discovered": "Ancient",
    "image": "https://images-of-elements.com/chromium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Chromium"
  },
  "Mn": {
    "name": "Manganese",
    "number": 25,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "54.938 u",
    "config": "[Ar] 3d⁵ 4s²",
    "oxidation": "+7, +4, +3, +2",
    "electronegativity": "1.55",
    "radius": "127 pm",
    "ionization": "7.434 eV",
    "affinity": "-0.03 eV",
    "melting": "1519 K",
    "boiling": "2334 K",
    "density": "7.47 g/cm³",
    "discovered": "1774",
    "image": "https://images-of-elements.com/manganese.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Manganese"
  },
  "Fe": {
    "name": "Iron",
    "number": 26,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "55.845 u",
    "config": "[Ar] 3d⁶ 4s²",
    "oxidation": "+2, +3",
    "electronegativity": "1.83",
    "radius": "126 pm",
    "ionization": "7.902 eV",
    "affinity": "0.16 eV",
    "melting": "1811 K",
    "boiling": "3134 K",
    "density": "7.874 g/cm³",
    "discovered": "Ancient",
    "image": "https://images-of-elements.com/iron.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Iron"
  },
  "Co": {
    "name": "Cobalt",
    "number": 27,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "58.933 u",
    "config": "[Ar] 3d⁷ 4s²",
    "oxidation": "+2, +3",
    "electronegativity": "1.88",
    "radius": "125 pm",
    "ionization": "7.881 eV",
    "affinity": "0.661 eV",
    "melting": "1768 K",
    "boiling": "3200 K",
    "density": "8.90 g/cm³",
    "discovered": "Ancient",
    "image": "https://images-of-elements.com/cobalt.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Cobalt"
  },
  "Ni": {
    "name": "Nickel",
    "number": 28,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "58.693 u",
    "config": "[Ar] 3d⁸ 4s²",
    "oxidation": "+2",
    "electronegativity": "1.91",
    "radius": "124 pm",
    "ionization": "7.639 eV",
    "affinity": "1.156 eV",
    "melting": "1728 K",
    "boiling": "3186 K",
    "density": "8.902 g/cm³",
    "discovered": "1751",
    "image": "https://images-of-elements.com/nickel.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Nickel"
  },
  "Cu": {
    "name": "Copper",
    "number": 29,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "63.546 u",
    "config": "[Ar] 3d¹⁰ 4s¹",
    "oxidation": "+2, +1",
    "electronegativity": "2.00",
    "radius": "128 pm",
    "ionization": "7.726 eV",
    "affinity": "1.226 eV",
    "melting": "1357.77 K",
    "boiling": "2835 K",
    "density": "8.96 g/cm³",
    "discovered": "Ancient",
    "image": "https://images-of-elements.com/copper.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Copper"
  },
  "Zn": {
    "name": "Zinc",
    "number": 30,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "65.38 u",
    "config": "[Ar] 3d¹⁰ 4s²",
    "oxidation": "+2",
    "electronegativity": "1.65",
    "radius": "134 pm",
    "ionization": "9.394 eV",
    "affinity": "-0.58 eV",
    "melting": "692.68 K",
    "boiling": "1180 K",
    "density": "7.13 g/cm³",
    "discovered": "Ancient",
    "image": "https://images-of-elements.com/zinc.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Zinc"
  },
  "Ga": {
    "name": "Gallium",
    "number": 31,
    "type": "Post-transition Metal",
    "state": "Solid",
    "mass": "69.723 u",
    "config": "[Ar] 3d¹⁰ 4s² 4p¹",
    "oxidation": "+3",
    "electronegativity": "1.81",
    "radius": "136 pm",
    "ionization": "6.00 eV",
    "affinity": "0.30 eV",
    "melting": "302.91 K",
    "boiling": "2477 K",
    "density": "5.91 g/cm³",
    "discovered": "1875",
    "image": "https://images-of-elements.com/gallium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Gallium"
  },
  "Ge": {
    "name": "Germanium",
    "number": 32,
    "type": "Metalloid",
    "state": "Solid",
    "mass": "72.63 u",
    "config": "[Ar] 3d¹⁰ 4s² 4p²",
    "oxidation": "+4, +2, -4",
    "electronegativity": "2.01",
    "radius": "125 pm",
    "ionization": "7.899 eV",
    "affinity": "1.233 eV",
    "melting": "1211.4 K",
    "boiling": "3106 K",
    "density": "5.323 g/cm³",
    "discovered": "1886",
    "image": "https://images-of-elements.com/germanium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Germanium"
  },
  "As": {
    "name": "Arsenic",
    "number": 33,
    "type": "Metalloid",
    "state": "Solid",
    "mass": "74.922 u",
    "config": "[Ar] 3d¹⁰ 4s² 4p³",
    "oxidation": "+5, +3, -3",
    "electronegativity": "2.18",
    "radius": "114 pm",
    "ionization": "9.789 eV",
    "affinity": "0.815 eV",
    "melting": "1090 K",
    "boiling": "887 K (sublimes)",
    "density": "5.727 g/cm³",
    "discovered": "Ancient",
    "image": "https://images-of-elements.com/arsenic.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Arsenic"
  },
  "Se": {
    "name": "Selenium",
    "number": 34,
    "type": "Nonmetal",
    "state": "Solid",
    "mass": "78.971 u",
    "config": "[Ar] 3d¹⁰ 4s² 4p⁴",
    "oxidation": "+6, +4, -2",
    "electronegativity": "2.55",
    "radius": "103 pm",
    "ionization": "9.752 eV",
    "affinity": "2.021 eV",
    "melting": "494 K",
    "boiling": "958 K",
    "density": "4.819 g/cm³",
    "discovered": "1817",
    "image": "https://images-of-elements.com/selenium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Selenium"
  },
  "Br": {
    "name": "Bromine",
    "number": 35,
    "type": "Halogen",
    "state": "Liquid",
    "mass": "79.904 u",
    "config": "[Ar] 3d¹⁰ 4s² 4p⁵",
    "oxidation": "-1, +1, +3, +5",
    "electronegativity": "2.96",
    "radius": "94 pm",
    "ionization": "11.814 eV",
    "affinity": "3.364 eV",
    "melting": "265.8 K",
    "boiling": "332.0 K",
    "density": "3.12 g/cm³",
    "discovered": "1826",
    "image": "https://images-of-elements.com/bromine.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Bromine"
  },
  "Kr": {
    "name": "Krypton",
    "number": 36,
    "type": "Noble Gas",
    "state": "Gas",
    "mass": "83.80 u",
    "config": "[Ar] 3d¹⁰ 4s² 4p⁶",
    "oxidation": "0, +2",
    "electronegativity": "N/A",
    "radius": "88 pm",
    "ionization": "14.00 eV",
    "affinity": "-1.07 eV",
    "melting": "115.78 K",
    "boiling": "119.93 K",
    "density": "0.003733 g/cm³",
    "discovered": "1898",
    "image": "https://images-of-elements.com/krypton.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Krypton"
  },
  "Rb": {
    "name": "Rubidium",
    "number": 37,
    "type": "Alkali Metal",
    "state": "Solid",
    "mass": "85.468 u",
    "config": "[Kr] 5s¹",
    "oxidation": "+1",
    "electronegativity": "0.82",
    "radius": "248 pm",
    "ionization": "4.177 eV",
    "affinity": "0.486 eV",
    "melting": "312.46 K",
    "boiling": "961 K",
    "density": "1.532 g/cm³",
    "discovered": "1861",
    "image": "https://images-of-elements.com/rubidium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Rubidium"
  },
  "Sr": {
    "name": "Strontium",
    "number": 38,
    "type": "Alkaline Earth Metal",
    "state": "Solid",
    "mass": "87.62 u",
    "config": "[Kr] 5s²",
    "oxidation": "+2",
    "electronegativity": "0.95",
    "radius": "215 pm",
    "ionization": "5.695 eV",
    "affinity": "0.052 eV",
    "melting": "1050 K",
    "boiling": "1655 K",
    "density": "2.64 g/cm³",
    "discovered": "1790",
    "image": "https://images-of-elements.com/strontium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Strontium"
  },
  "Y": {
    "name": "Yttrium",
    "number": 39,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "88.906 u",
    "config": "[Kr] 4d¹ 5s²",
    "oxidation": "+3",
    "electronegativity": "1.22",
    "radius": "180 pm",
    "ionization": "6.217 eV",
    "affinity": "0.307 eV",
    "melting": "1789 K",
    "boiling": "3609 K",
    "density": "4.472 g/cm³",
    "discovered": "1794",
    "image": "https://images-of-elements.com/yttrium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Yttrium"
  },
  "Zr": {
    "name": "Zirconium",
    "number": 40,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "91.224 u",
    "config": "[Kr] 4d² 5s²",
    "oxidation": "+4",
    "electronegativity": "1.33",
    "radius": "159 pm",
    "ionization": "6.634 eV",
    "affinity": "0.426 eV",
    "melting": "2128 K",
    "boiling": "4682 K",
    "density": "6.52 g/cm³",
    "discovered": "1789",
    "image": "https://images-of-elements.com/zirconium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Zirconium"
  },
  "Nb": {
    "name": "Niobium",
    "number": 41,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "92.906 u",
    "config": "[Kr] 4d⁴ 5s¹",
    "oxidation": "+5, +3",
    "electronegativity": "1.6",
    "radius": "146 pm",
    "ionization": "6.759 eV",
    "affinity": "0.895 eV",
    "melting": "2750 K",
    "boiling": "5017 K",
    "density": "8.57 g/cm³",
    "discovered": "1801",
    "image": "https://images-of-elements.com/niobium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Niobium"
  },
  "Mo": {
    "name": "Molybdenum",
    "number": 42,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "95.95 u",
    "config": "[Kr] 4d⁵ 5s¹",
    "oxidation": "+6, +5, +4, +3",
    "electronegativity": "2.16",
    "radius": "139 pm",
    "ionization": "7.092 eV",
    "affinity": "0.746 eV",
    "melting": "2896 K",
    "boiling": "4912 K",
    "density": "10.28 g/cm³",
    "discovered": "1778",
    "image": "https://images-of-elements.com/molybdenum.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Molybdenum"
  },
  "Tc": {
    "name": "Technetium",
    "number": 43,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "98 u",
    "config": "[Kr] 4d⁵ 5s²",
    "oxidation": "+7, +6, +4",
    "electronegativity": "1.9",
    "radius": "136 pm",
    "ionization": "7.28 eV",
    "affinity": "0.55 eV",
    "melting": "2430 K",
    "boiling": "4538 K",
    "density": "11.5 g/cm³",
    "discovered": "1937",
    "image": "https://images-of-elements.com/technetium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Technetium"
  },
  "Ru": {
    "name": "Ruthenium",
    "number": 44,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "101.07 u",
    "config": "[Kr] 4d⁷ 5s¹",
    "oxidation": "+4, +3",
    "electronegativity": "2.2",
    "radius": "134 pm",
    "ionization": "7.36 eV",
    "affinity": "1.05 eV",
    "melting": "2607 K",
    "boiling": "4423 K",
    "density": "12.45 g/cm³",
    "discovered": "1844",
    "image": "https://images-of-elements.com/ruthenium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Ruthenium"
  },
  "Rh": {
    "name": "Rhodium",
    "number": 45,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "102.91 u",
    "config": "[Kr] 4d⁸ 5s¹",
    "oxidation": "+3, +4",
    "electronegativity": "2.28",
    "radius": "134 pm",
    "ionization": "7.46 eV",
    "affinity": "1.14 eV",
    "melting": "2237 K",
    "boiling": "3968 K",
    "density": "12.41 g/cm³",
    "discovered": "1803",
    "image": "https://images-of-elements.com/rhodium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Rhodium"
  },
  "Pd": {
    "name": "Palladium",
    "number": 46,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "106.42 u",
    "config": "[Kr] 4d¹⁰",
    "oxidation": "+2, +4",
    "electronegativity": "2.20",
    "radius": "137 pm",
    "ionization": "8.33 eV",
    "affinity": "0.56 eV",
    "melting": "1828 K",
    "boiling": "3236 K",
    "density": "12.023 g/cm³",
    "discovered": "1803",
    "image": "https://images-of-elements.com/palladium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Palladium"
  },
  "Ag": {
    "name": "Silver",
    "number": 47,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "107.87 u",
    "config": "[Kr] 4d¹⁰ 5s¹",
    "oxidation": "+1",
    "electronegativity": "1.93",
    "radius": "144 pm",
    "ionization": "7.576 eV",
    "affinity": "1.303 eV",
    "melting": "1234.93 K",
    "boiling": "2435 K",
    "density": "10.49 g/cm³",
    "discovered": "Ancient",
    "image": "https://images-of-elements.com/silver.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Silver"
  },
  "Cd": {
    "name": "Cadmium",
    "number": 48,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "112.41 u",
    "config": "[Kr] 4d¹⁰ 5s²",
    "oxidation": "+2",
    "electronegativity": "1.69",
    "radius": "151 pm",
    "ionization": "8.994 eV",
    "affinity": "-0.62 eV",
    "melting": "594.22 K",
    "boiling": "1040 K",
    "density": "8.65 g/cm³",
    "discovered": "1817",
    "image": "https://images-of-elements.com/cadmium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Cadmium"
  },
  "In": {
    "name": "Indium",
    "number": 49,
    "type": "Post-transition Metal",
    "state": "Solid",
    "mass": "114.82 u",
    "config": "[Kr] 4d¹⁰ 5s² 5p¹",
    "oxidation": "+3",
    "electronegativity": "1.78",
    "radius": "156 pm",
    "ionization": "5.786 eV",
    "affinity": "0.3 eV",
    "melting": "429.75 K",
    "boiling": "2345 K",
    "density": "7.31 g/cm³",
    "discovered": "1863",
    "image": "https://images-of-elements.com/indium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Indium"
  },
  "Sn": {
    "name": "Tin",
    "number": 50,
    "type": "Post-transition Metal",
    "state": "Solid",
    "mass": "118.71 u",
    "config": "[Kr] 4d¹⁰ 5s² 5p²",
    "oxidation": "+4, +2, -4",
    "electronegativity": "1.96",
    "radius": "145 pm",
    "ionization": "7.344 eV",
    "affinity": "1.107 eV",
    "melting": "505.08 K",
    "boiling": "2875 K",
    "density": "7.265 g/cm³",
    "discovered": "Ancient",
    "image": "https://images-of-elements.com/tin.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Tin"
  },
  "Sb": {
    "name": "Antimony",
    "number": 51,
    "type": "Metalloid",
    "state": "Solid",
    "mass": "121.76 u",
    "config": "[Kr] 4d¹⁰ 5s² 5p³",
    "oxidation": "+5, +3, -3",
    "electronegativity": "2.05",
    "radius": "133 pm",
    "ionization": "8.608 eV",
    "affinity": "1.07 eV",
    "melting": "903.78 K",
    "boiling": "1860 K",
    "density": "6.697 g/cm³",
    "discovered": "Ancient",
    "image": "https://images-of-elements.com/antimony.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Antimony"
  },
  "Te": {
    "name": "Tellurium",
    "number": 52,
    "type": "Metalloid",
    "state": "Solid",
    "mass": "127.6 u",
    "config": "[Kr] 4d¹⁰ 5s² 5p⁴",
    "oxidation": "+6, +4, -2",
    "electronegativity": "2.1",
    "radius": "123 pm",
    "ionization": "9.01 eV",
    "affinity": "1.971 eV",
    "melting": "722.66 K",
    "boiling": "1261 K",
    "density": "6.24 g/cm³",
    "discovered": "1782",
    "image": "https://images-of-elements.com/tellurium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Tellurium"
  },
  "I": {
    "name": "Iodine",
    "number": 53,
    "type": "Halogen",
    "state": "Solid",
    "mass": "126.90 u",
    "config": "[Kr] 4d¹⁰ 5s² 5p⁵",
    "oxidation": "-1, +1, +3, +5, +7",
    "electronegativity": "2.66",
    "radius": "115 pm",
    "ionization": "10.451 eV",
    "affinity": "3.059 eV",
    "melting": "386.85 K",
    "boiling": "457.4 K",
    "density": "4.93 g/cm³",
    "discovered": "1811",
    "image": "https://images-of-elements.com/iodine.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Iodine"
  },
    "Xe": {
    "name": "Xenon",
    "number": 54,
    "type": "Noble Gas",
    "state": "Gas",
    "mass": "131.29 u",
    "config": "[Kr] 4d¹⁰ 5s² 5p⁶",
    "oxidation": "0, +2, +4, +6, +8",
    "electronegativity": "N/A",
    "radius": "140 pm",
    "ionization": "12.1298 eV",
    "affinity": "-0.043 eV",
    "melting": "161.4 K",
    "boiling": "165.0 K",
    "density": "0.005887 g/cm³",
    "discovered": "1898",
    "image": "https://images-of-elements.com/xenon.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Xenon"
  },
  "Cs": {
    "name": "Cesium",
    "number": 55,
    "type": "Alkali Metal",
    "state": "Solid",
    "mass": "132.905 u",
    "config": "[Xe] 6s¹",
    "oxidation": "+1",
    "electronegativity": "0.79",
    "radius": "260 pm",
    "ionization": "3.8939 eV",
    "affinity": "0.4715 eV",
    "melting": "301.7 K",
    "boiling": "944 K",
    "density": "1.93 g/cm³",
    "discovered": "1860",
    "image": "https://images-of-elements.com/cesium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Cesium"
  },
  "Ba": {
    "name": "Barium",
    "number": 56,
    "type": "Alkaline Earth Metal",
    "state": "Solid",
    "mass": "137.33 u",
    "config": "[Xe] 6s²",
    "oxidation": "+2",
    "electronegativity": "0.89",
    "radius": "215 pm",
    "ionization": "5.2117 eV",
    "affinity": "N/A",
    "melting": "1000 K",
    "boiling": "2170 K",
    "density": "3.51 g/cm³",
    "discovered": "1808",
    "image": "https://images-of-elements.com/barium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Barium"
  },
  "La": {
    "name": "Lanthanum",
    "number": 57,
    "type": "Lanthanide",
    "state": "Solid",
    "mass": "138.905 u",
    "config": "[Xe] 5d¹ 6s²",
    "oxidation": "+3",
    "electronegativity": "1.10",
    "radius": "195 pm",
    "ionization": "5.5769 eV",
    "affinity": "0.5 eV",
    "melting": "1193 K",
    "boiling": "3735 K",
    "density": "6.15 g/cm³",
    "discovered": "1839",
    "image": "https://images-of-elements.com/lanthanum.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Lanthanum"
  },
  "Ce": {
    "name": "Cerium",
    "number": 58,
    "type": "Lanthanide",
    "state": "Solid",
    "mass": "140.12 u",
    "config": "[Xe] 4f¹ 5d¹ 6s²",
    "oxidation": "+3, +4",
    "electronegativity": "1.12",
    "radius": "183 pm",
    "ionization": "5.5387 eV",
    "affinity": "N/A",
    "melting": "1071 K",
    "boiling": "3716 K",
    "density": "6.77 g/cm³",
    "discovered": "1803",
    "image": "https://images-of-elements.com/cerium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Cerium"
  },
  "Pr": {
    "name": "Praseodymium",
    "number": 59,
    "type": "Lanthanide",
    "state": "Solid",
    "mass": "140.908 u",
    "config": "[Xe] 4f³ 6s²",
    "oxidation": "+3",
    "electronegativity": "1.13",
    "radius": "182 pm",
    "ionization": "5.473 eV",
    "affinity": "N/A",
    "melting": "1208 K",
    "boiling": "3793 K",
    "density": "6.77 g/cm³",
    "discovered": "1885",
    "image": "https://images-of-elements.com/praseodymium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Praseodymium"
  },
  "Nd": {
    "name": "Neodymium",
    "number": 60,
    "type": "Lanthanide",
    "state": "Solid",
    "mass": "144.24 u",
    "config": "[Xe] 4f⁴ 6s²",
    "oxidation": "+3",
    "electronegativity": "1.14",
    "radius": "181 pm",
    "ionization": "5.525 eV",
    "affinity": "N/A",
    "melting": "1297 K",
    "boiling": "3347 K",
    "density": "7.01 g/cm³",
    "discovered": "1885",
    "image": "https://images-of-elements.com/neodymium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Neodymium"
  },
  "Pm": {
    "name": "Promethium",
    "number": 61,
    "type": "Lanthanide",
    "state": "Solid",
    "mass": "145 u",
    "config": "[Xe] 4f⁵ 6s²",
    "oxidation": "+3",
    "electronegativity": "1.13",
    "radius": "183 pm",
    "ionization": "5.55 eV",
    "affinity": "N/A",
    "melting": "1315 K",
    "boiling": "3273 K",
    "density": "7.26 g/cm³",
    "discovered": "1945",
    "image": "https://images-of-elements.com/promethium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Promethium"
  },
  "Sm": {
    "name": "Samarium",
    "number": 62,
    "type": "Lanthanide",
    "state": "Solid",
    "mass": "150.36 u",
    "config": "[Xe] 4f⁶ 6s²",
    "oxidation": "+3",
    "electronegativity": "1.17",
    "radius": "180 pm",
    "ionization": "5.6437 eV",
    "affinity": "N/A",
    "melting": "1345 K",
    "boiling": "2067 K",
    "density": "7.52 g/cm³",
    "discovered": "1879",
    "image": "https://images-of-elements.com/samarium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Samarium"
  },
  "Eu": {
    "name": "Europium",
    "number": 63,
    "type": "Lanthanide",
    "state": "Solid",
    "mass": "151.964 u",
    "config": "[Xe] 4f⁷ 6s²",
    "oxidation": "+2, +3",
    "electronegativity": "1.20",
    "radius": "185 pm",
    "ionization": "5.6704 eV",
    "affinity": "N/A",
    "melting": "1099 K",
    "boiling": "1802 K",
    "density": "5.244 g/cm³",
    "discovered": "1890",
    "image": "https://images-of-elements.com/europium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Europium"
  },
  "Gd": {
    "name": "Gadolinium",
    "number": 64,
    "type": "Lanthanide",
    "state": "Solid",
    "mass": "157.25 u",
    "config": "[Xe] 4f⁷ 5d¹ 6s²",
    "oxidation": "+3",
    "electronegativity": "1.20",
    "radius": "179 pm",
    "ionization": "6.150 eV",
    "affinity": "N/A",
    "melting": "1586 K",
    "boiling": "3546 K",
    "density": "7.90 g/cm³",
    "discovered": "1880",
    "image": "https://images-of-elements.com/gadolinium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Gadolinium"
  },
  "Tb": {
    "name": "Terbium",
    "number": 65,
    "type": "Lanthanide",
    "state": "Solid",
    "mass": "158.925 u",
    "config": "[Xe] 4f⁹ 6s²",
    "oxidation": "+3",
    "electronegativity": "1.22",
    "radius": "176 pm",
    "ionization": "5.864 eV",
    "affinity": "N/A",
    "melting": "1629 K",
    "boiling": "3503 K",
    "density": "8.23 g/cm³",
    "discovered": "1843",
    "image": "https://images-of-elements.com/terbium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Terbium"
  },
  "Dy": {
    "name": "Dysprosium",
    "number": 66,
    "type": "Lanthanide",
    "state": "Solid",
    "mass": "162.50 u",
    "config": "[Xe] 4f¹⁰ 6s²",
    "oxidation": "+3",
    "electronegativity": "1.22",
    "radius": "177 pm",
    "ionization": "5.939 eV",
    "affinity": "N/A",
    "melting": "1680 K",
    "boiling": "2840 K",
    "density": "8.54 g/cm³",
    "discovered": "1886",
    "image": "https://images-of-elements.com/dysprosium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Dysprosium"
  },
  "Ho": {
    "name": "Holmium",
    "number": 67,
    "type": "Lanthanide",
    "state": "Solid",
    "mass": "164.930 u",
    "config": "[Xe] 4f¹¹ 6s²",
    "oxidation": "+3",
    "electronegativity": "1.23",
    "radius": "176 pm",
    "ionization": "6.0215 eV",
    "affinity": "N/A",
    "melting": "1734 K",
    "boiling": "2943 K",
    "density": "8.79 g/cm³",
    "discovered": "1878",
    "image": "https://images-of-elements.com/holmium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Holmium"
  },
  "Er": {
    "name": "Erbium",
    "number": 68,
    "type": "Lanthanide",
    "state": "Solid",
    "mass": "167.26 u",
    "config": "[Xe] 4f¹² 6s²",
    "oxidation": "+3",
    "electronegativity": "1.24",
    "radius": "175 pm",
    "ionization": "6.1077 eV",
    "affinity": "N/A",
    "melting": "1802 K",
    "boiling": "3141 K",
    "density": "9.066 g/cm³",
    "discovered": "1842",
    "image": "https://images-of-elements.com/erbium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Erbium"
  },
  "Tm": {
    "name": "Thulium",
    "number": 69,
    "type": "Lanthanide",
    "state": "Solid",
    "mass": "168.934 u",
    "config": "[Xe] 4f¹³ 6s²",
    "oxidation": "+3",
    "electronegativity": "1.25",
    "radius": "174 pm",
    "ionization": "6.1843 eV",
    "affinity": "N/A",
    "melting": "1818 K",
    "boiling": "2223 K",
    "density": "9.32 g/cm³",
    "discovered": "1879",
    "image": "https://images-of-elements.com/thulium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Thulium"
  },
  "Yb": {
    "name": "Ytterbium",
    "number": 70,
    "type": "Lanthanide",
    "state": "Solid",
    "mass": "173.05 u",
    "config": "[Xe] 4f¹⁴ 6s²",
    "oxidation": "+2, +3",
    "electronegativity": "1.26",
    "radius": "170 pm",
    "ionization": "6.2542 eV",
    "affinity": "N/A",
    "melting": "1097 K",
    "boiling": "1469 K",
    "density": "6.90 g/cm³",
    "discovered": "1878",
    "image": "https://images-of-elements.com/ytterbium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Ytterbium"
  },
  "Lu": {
    "name": "Lutetium",
    "number": 71,
    "type": "Lanthanide",
    "state": "Solid",
    "mass": "174.967 u",
    "config": "[Xe] 4f¹⁴ 5d¹ 6s²",
    "oxidation": "+3",
    "electronegativity": "1.27",
    "radius": "173 pm",
    "ionization": "5.4259 eV",
    "affinity": "N/A",
    "melting": "1925 K",
    "boiling": "3675 K",
    "density": "9.841 g/cm³",
    "discovered": "1907",
    "image": "https://images-of-elements.com/lutetium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Lutetium"
  },
  "Hf": {
    "name": "Hafnium",
    "number": 72,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "178.49 u",
    "config": "[Xe] 4f¹⁴ 5d² 6s²",
    "oxidation": "+4",
    "electronegativity": "1.3",
    "radius": "159 pm",
    "ionization": "6.8251 eV",
    "affinity": "N/A",
    "melting": "2506 K",
    "boiling": "4876 K",
    "density": "13.31 g/cm³",
    "discovered": "1923",
    "image": "https://images-of-elements.com/hafnium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Hafnium"
  },
  "Ta": {
    "name": "Tantalum",
    "number": 73,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "180.948 u",
    "config": "[Xe] 4f¹⁴ 5d³ 6s²",
    "oxidation": "-1, +2, +3, +4, +5",
    "electronegativity": "1.5",
    "radius": "146 pm",
    "ionization": "7.89 eV",
    "affinity": "0.322 eV",
    "melting": "3290 K",
    "boiling": "5731 K",
    "density": "16.69 g/cm³",
    "discovered": "1802",
    "image": "https://images-of-elements.com/tantalum.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Tantalum"
  },
  "W": {
    "name": "Tungsten",
    "number": 74,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "183.84 u",
    "config": "[Xe] 4f¹⁴ 5d⁴ 6s²",
    "oxidation": "-2, +2, +3, +4, +5, +6",
    "electronegativity": "2.36",
    "radius": "139 pm",
    "ionization": "7.864 eV",
    "affinity": "0.815 eV",
    "melting": "3695 K",
    "boiling": "5934 K",
    "density": "19.25 g/cm³",
    "discovered": "1783",
    "image": "https://images-of-elements.com/tungsten.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Tungsten"
  },
  "Re": {
    "name": "Rhenium",
    "number": 75,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "186.207 u",
    "config": "[Xe] 4f¹⁴ 5d⁵ 6s²",
    "oxidation": "-1, +2, +3, +4, +5, +6, +7",
    "electronegativity": "1.9",
    "radius": "137 pm",
    "ionization": "7.88 eV",
    "affinity": "0.15 eV",
    "melting": "3459 K",
    "boiling": "5869 K",
    "density": "21.02 g/cm³",
    "discovered": "1925",
    "image": "https://images-of-elements.com/rhenium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Rhenium"
  },
  "Os": {
    "name": "Osmium",
    "number": 76,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "190.23 u",
    "config": "[Xe] 4f¹⁴ 5d⁶ 6s²",
    "oxidation": "-2, +2, +3, +4, +5, +6, +8",
    "electronegativity": "2.2",
    "radius": "135 pm",
    "ionization": "8.7 eV",
    "affinity": "1.1 eV",
    "melting": "3306 K",
    "boiling": "5285 K",
    "density": "22.59 g/cm³",
    "discovered": "1803",
    "image": "https://images-of-elements.com/osmium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Osmium"
  },
  "Ir": {
    "name": "Iridium",
    "number": 77,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "192.22 u",
    "config": "[Xe] 4f¹⁴ 5d⁷ 6s²",
    "oxidation": "-3, -1, +1, +2, +3, +4, +5, +6",
    "electronegativity": "2.20",
    "radius": "136 pm",
    "ionization": "9.1 eV",
    "affinity": "1.565 eV",
    "melting": "2719 K",
    "boiling": "4701 K",
    "density": "22.65 g/cm³",
    "discovered": "1803",
    "image": "https://images-of-elements.com/iridium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Iridium"
  },
  "Pt": {
    "name": "Platinum",
    "number": 78,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "195.08 u",
    "config": "[Xe] 4f¹⁴ 5d⁹ 6s¹",
    "oxidation": "-2, +1, +2, +3, +4, +5, +6",
    "electronegativity": "2.28",
    "radius": "139 pm",
    "ionization": "9.0 eV",
    "affinity": "2.125 eV",
    "melting": "2041 K",
    "boiling": "4098 K",
    "density": "21.45 g/cm³",
    "discovered": "1735",
    "image": "https://images-of-elements.com/platinum.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Platinum"
  },
  "Au": {
    "name": "Gold",
    "number": 79,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "196.967 u",
    "config": "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    "oxidation": "-1, +1, +2, +3, +5",
    "electronegativity": "2.54",
    "radius": "144 pm",
    "ionization": "9.2255 eV",
    "affinity": "2.3086 eV",
    "melting": "1337.33 K",
    "boiling": "3243 K",
    "density": "19.30 g/cm³",
    "discovered": "Ancient",
    "image": "https://images-of-elements.com/gold.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Gold"},
  "Hg": {
    "name": "Mercury",
    "number": 80,
    "type": "Transition Metal",
    "state": "Liquid",
    "mass": "200.59 u",
    "config": "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    "oxidation": "+1, +2, +4",
    "electronegativity": "2.00",
    "radius": "149 pm",
    "ionization": "10.434 eV",
    "affinity": "-0.48 eV",
    "melting": "234.32 K",
    "boiling": "629.88 K",
    "density": "13.534 g/cm³",
    "discovered": "Ancient",
    "image": "https://images-of-elements.com/mercury.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Mercury_(element)"
  },
  "Tl": {
    "name": "Thallium",
    "number": 81,
    "type": "Post-transition Metal",
    "state": "Solid",
    "mass": "204.38 u",
    "config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    "oxidation": "+1, +3",
    "electronegativity": "2.04",
    "radius": "148 pm",
    "ionization": "6.108 eV",
    "affinity": "0.377 eV",
    "melting": "577 K",
    "boiling": "1746 K",
    "density": "11.85 g/cm³",
    "discovered": "1861",
    "image": "https://images-of-elements.com/thallium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Thallium"
  },
  "Pb": {
    "name": "Lead",
    "number": 82,
    "type": "Post-transition Metal",
    "state": "Solid",
    "mass": "207.2 u",
    "config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    "oxidation": "-4, +2, +4",
    "electronegativity": "2.33",
    "radius": "146 pm",
    "ionization": "7.4167 eV",
    "affinity": "0.36 eV",
    "melting": "600.61 K",
    "boiling": "2022 K",
    "density": "11.34 g/cm³",
    "discovered": "Ancient",
    "image": "https://images-of-elements.com/lead.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Lead"
  },
  "Bi": {
    "name": "Bismuth",
    "number": 83,
    "type": "Post-transition Metal",
    "state": "Solid",
    "mass": "208.980 u",
    "config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    "oxidation": "-3, +3, +5",
    "electronegativity": "2.02",
    "radius": "143 pm",
    "ionization": "7.2856 eV",
    "affinity": "0.942 eV",
    "melting": "544.7 K",
    "boiling": "1837 K",
    "density": "9.78 g/cm³",
    "discovered": "Ancient",
    "image": "https://images-of-elements.com/bismuth.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Bismuth"
  },
  "Po": {
    "name": "Polonium",
    "number": 84,
    "type": "Post-transition Metal",
    "state": "Solid",
    "mass": "209 u",
    "config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    "oxidation": "-2, +2, +4",
    "electronegativity": "2.0",
    "radius": "167 pm",
    "ionization": "8.438 eV",
    "affinity": "N/A",
    "melting": "527 K",
    "boiling": "1235 K",
    "density": "9.196 g/cm³",
    "discovered": "1898",
    "image": "https://images-of-elements.com/polonium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Polonium"
  },
  "At": {
    "name": "Astatine",
    "number": 85,
    "type": "Metalloid",
    "state": "Solid",
    "mass": "210 u",
    "config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    "oxidation": "-1, +1, +3, +5, +7",
    "electronegativity": "2.0",
    "radius": "145 pm",
    "ionization": "9.3 eV",
    "affinity": "N/A",
    "melting": "573 K",
    "boiling": "610 K",
    "density": "N/A",
    "discovered": "1940",
    "image": "https://images-of-elements.com/astatine.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Astatine"
  },
  "Rn": {
    "name": "Radon",
    "number": 86,
    "type": "Noble Gas",
    "state": "Gas",
    "mass": "222 u",
    "config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    "oxidation": "0, +2",
    "electronegativity": "N/A",
    "radius": "150 pm",
    "ionization": "10.7485 eV",
    "affinity": "-0.21 eV",
    "melting": "202 K",
    "boiling": "211.3 K",
    "density": "0.00973 g/cm³",
    "discovered": "1900",
    "image": "https://images-of-elements.com/radon.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Radon"
  },
  "Fr": {
    "name": "Francium",
    "number": 87,
    "type": "Alkali Metal",
    "state": "Solid",
    "mass": "223 u",
    "config": "[Rn] 7s¹",
    "oxidation": "+1",
    "electronegativity": "0.7",
    "radius": "N/A",
    "ionization": "4.075 eV",
    "affinity": "0.47 eV",
    "melting": "300 K",
    "boiling": "950 K",
    "density": "N/A",
    "discovered": "1939",
    "image": "https://images-of-elements.com/francium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Francium"
  },
  "Ra": {
    "name": "Radium",
    "number": 88,
    "type": "Alkaline Earth Metal",
    "state": "Solid",
    "mass": "226 u",
    "config": "[Rn] 7s²",
    "oxidation": "+2",
    "electronegativity": "0.9",
    "radius": "N/A",
    "ionization": "5.2784 eV",
    "affinity": "N/A",
    "melting": "973 K",
    "boiling": "1413 K",
    "density": "5.0 g/cm³",
    "discovered": "1898",
    "image": "https://images-of-elements.com/radium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Radium"
  },
  "Ac": {
    "name": "Actinium",
    "number": 89,
    "type": "Actinide",
    "state": "Solid",
    "mass": "227 u",
    "config": "[Rn] 6d¹ 7s²",
    "oxidation": "+3",
    "electronegativity": "1.1",
    "radius": "N/A",
    "ionization": "5.17 eV",
    "affinity": "N/A",
    "melting": "1323 K",
    "boiling": "3473 K",
    "density": "10.07 g/cm³",
    "discovered": "1899",
    "image": "https://images-of-elements.com/actinium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Actinium"
  },
  "Th": {
    "name": "Thorium",
    "number": 90,
    "type": "Actinide",
    "state": "Solid",
    "mass": "232.038 u",
    "config": "[Rn] 6d² 7s²",
    "oxidation": "+4",
    "electronegativity": "1.3",
    "radius": "N/A",
    "ionization": "6.3067 eV",
    "affinity": "N/A",
    "melting": "2023 K",
    "boiling": "5061 K",
    "density": "11.72 g/cm³",
    "discovered": "1828",
    "image": "https://images-of-elements.com/thorium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Thorium"
  },
  "Pa": {
    "name": "Protactinium",
    "number": 91,
    "type": "Actinide",
    "state": "Solid",
    "mass": "231.036 u",
    "config": "[Rn] 5f² 6d¹ 7s²",
    "oxidation": "+4, +5",
    "electronegativity": "1.5",
    "radius": "N/A",
    "ionization": "5.89 eV",
    "affinity": "N/A",
    "melting": "1841 K",
    "boiling": "4300 K",
    "density": "15.37 g/cm³",
    "discovered": "1913",
    "image": "https://images-of-elements.com/protactinium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Protactinium"
  },
  "U": {
    "name": "Uranium",
    "number": 92,
    "type": "Actinide",
    "state": "Solid",
    "mass": "238.029 u",
    "config": "[Rn] 5f³ 6d¹ 7s²",
    "oxidation": "+2, +3, +4, +5, +6",
    "electronegativity": "1.38",
    "radius": "N/A",
    "ionization": "6.194 eV",
    "affinity": "N/A",
    "melting": "1405.3 K",
    "boiling": "4404 K",
    "density": "19.05 g/cm³",
    "discovered": "1789",
    "image": "https://images-of-elements.com/uranium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Uranium"
  },
  "Np": {
    "name": "Neptunium",
    "number": 93,
    "type": "Actinide",
    "state": "Solid",
    "mass": "237 u",
    "config": "[Rn] 5f⁴ 6d¹ 7s²",
    "oxidation": "+3, +4, +5, +6, +7",
    "electronegativity": "1.36",
    "radius": "N/A",
    "ionization": "6.2657 eV",
    "affinity": "N/A",
    "melting": "912 K",
    "boiling": "4273 K",
    "density": "20.45 g/cm³",
    "discovered": "1940",
    "image": "https://images-of-elements.com/neptunium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Neptunium"
  },
  "Pu": {
    "name": "Plutonium",
    "number": 94,
    "type": "Actinide",
    "state": "Solid",
    "mass": "244 u",
    "config": "[Rn] 5f⁶ 7s²",
    "oxidation": "+2, +3, +4, +5, +6, +7",
    "electronegativity": "1.28",
    "radius": "N/A",
    "ionization": "6.0262 eV",
    "affinity": "N/A",
    "melting": "912.5 K",
    "boiling": "3503 K",
    "density": "19.816 g/cm³",
    "discovered": "1940",
    "image": "https://images-of-elements.com/plutonium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Plutonium"
  },
  "Am": {
    "name": "Americium",
    "number": 95,
    "type": "Actinide",
    "state": "Solid",
    "mass": "243 u",
    "config": "[Rn] 5f⁷ 7s²",
    "oxidation": "+2, +3, +4, +5, +6, +7",
    "electronegativity": "1.3",
    "radius": "N/A",
    "ionization": "5.9738 eV",
    "affinity": "N/A",
    "melting": "1449 K",
    "boiling": "2880 K",
    "density": "13.69 g/cm³",
    "discovered": "1944",
    "image": "https://images-of-elements.com/americium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Americium"
  },
  "Cm": {
    "name": "Curium",
    "number": 96,
    "type": "Actinide",
    "state": "Solid",
    "mass": "247 u",
    "config": "[Rn] 5f⁷ 6d¹ 7s²",
    "oxidation": "+3, +4, +5",
    "electronegativity": "1.3",
    "radius": "N/A",
    "ionization": "6.07 eV",
    "affinity": "N/A",
    "melting": "1613 K",
    "boiling": "3383 K",
    "density": "13.51 g/cm³",
    "discovered": "1944",
    "image": "https://images-of-elements.com/curium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Curium"
  },
  "Bk": {
    "name": "Berkelium",
    "number": 97,
    "type": "Actinide",
    "state": "Solid",
    "mass": "247 u",
    "config": "[Rn] 5f⁹ 7s²",
    "oxidation": "+3, +4",
    "electronegativity": "1.3",
    "radius": "N/A",
    "ionization": "6.1979 eV",
    "affinity": "N/A",
    "melting": "1259 K",
    "boiling": "N/A",
    "density": "14.78 g/cm³",
    "discovered": "1949",
    "image": "https://images-of-elements.com/berkelium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Berkelium"
  },
  "Cf": {
    "name": "Californium",
    "number": 98,
    "type": "Actinide",
    "state": "Solid",
    "mass": "251 u",
    "config": "[Rn] 5f¹⁰ 7s²",
    "oxidation": "+2, +3, +4",
    "electronegativity": "1.3",
    "radius": "N/A",
    "ionization": "6.2817 eV",
    "affinity": "N/A",
    "melting": "1173 K",
    "boiling": "N/A",
    "density": "15.1 g/cm³",
    "discovered": "1950",
    "image": "https://images-of-elements.com/californium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Californium"
  },
  "Es": {
    "name": "Einsteinium",
    "number": 99,
    "type": "Actinide",
    "state": "Solid",
    "mass": "252 u",
    "config": "[Rn] 5f¹¹ 7s²",
    "oxidation": "+2, +3",
    "electronegativity": "1.3",
    "radius": "N/A",
    "ionization": "6.42 eV",
    "affinity": "N/A",
    "melting": "1133 K",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "1952",
    "image": "https://images-of-elements.com/einsteinium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Einsteinium"
  },
  "Fm": {
    "name": "Fermium",
    "number": 100,
    "type": "Actinide",
    "state": "Solid",
    "mass": "257 u",
    "config": "[Rn] 5f¹² 7s²",
    "oxidation": "+2, +3",
    "electronegativity": "1.3",
    "radius": "N/A",
    "ionization": "6.5 eV",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "1952",
    "image": "https://images-of-elements.com/fermium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Fermium"
  },
  "Md": {
    "name": "Mendelevium",
    "number": 101,
    "type": "Actinide",
    "state": "Solid",
    "mass": "258 u",
    "config": "[Rn] 5f¹³ 7s²",
    "oxidation": "+2, +3",
    "electronegativity": "1.3",
    "radius": "N/A",
    "ionization": "6.58 eV",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "1955",
    "image": "https://images-of-elements.com/mendelevium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Mendelevium"
  },
  "No": {
    "name": "Nobelium",
    "number": 102,
    "type": "Actinide",
    "state": "Solid",
    "mass": "259 u",
    "config": "[Rn] 5f¹⁴ 7s²",
    "oxidation": "+2, +3",
    "electronegativity": "1.3",
    "radius": "N/A",
    "ionization": "6.65 eV",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "1958",
    "image": "https://images-of-elements.com/nobelium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Nobelium"
  },
  "Lr": {
    "name": "Lawrencium",
    "number": 103,
    "type": "Actinide",
    "state": "Solid",
    "mass": "262 u",
    "config": "[Rn] 5f¹⁴ 6d¹ 7s²",
    "oxidation": "+3",
    "electronegativity": "1.3",
    "radius": "N/A",
    "ionization": "6.7 eV",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "1961",
    "image": "https://images-of-elements.com/lawrencium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Lawrencium"
  },
  "Rf": {
    "name": "Rutherfordium",
    "number": 104,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "267 u",
    "config": "[Rn] 5f¹⁴ 6d² 7s²",
    "oxidation": "+4",
    "electronegativity": "N/A",
    "radius": "N/A",
    "ionization": "N/A",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "1964",
    "image": "https://images-of-elements.com/rutherfordium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Rutherfordium"
  },
  "Db": {
    "name": "Dubnium",
    "number": 105,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "270 u",
    "config": "[Rn] 5f¹⁴ 6d³ 7s²",
    "oxidation": "+3, +4, +5",
    "electronegativity": "N/A",
    "radius": "N/A",
    "ionization": "N/A",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "1968",
    "image": "https://images-of-elements.com/dubnium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Dubnium"
  },
    "Sg": {
    "name": "Seaborgium",
    "number": 106,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "271 u",
    "config": "[Rn] 5f¹⁴ 6d⁴ 7s²",
    "oxidation": "+6",
    "electronegativity": "N/A",
    "radius": "N/A",
    "ionization": "N/A",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "1974",
    "image": "https://images-of-elements.com/seaborgium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Seaborgium"
  },
  "Bh": {
    "name": "Bohrium",
    "number": 107,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "272 u",
    "config": "[Rn] 5f¹⁴ 6d⁵ 7s²",
    "oxidation": "+3, +4, +5, +7",
    "electronegativity": "N/A",
    "radius": "N/A",
    "ionization": "N/A",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "1981",
    "image": "https://images-of-elements.com/bohrium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Bohrium"
  },
  "Hs": {
    "name": "Hassium",
    "number": 108,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "270 u",
    "config": "[Rn] 5f¹⁴ 6d⁶ 7s²",
    "oxidation": "+4, +8",
    "electronegativity": "N/A",
    "radius": "N/A",
    "ionization": "N/A",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "1984",
    "image": "https://images-of-elements.com/hassium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Hassium"
  },
  "Mt": {
    "name": "Meitnerium",
    "number": 109,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "276 u",
    "config": "[Rn] 5f¹⁴ 6d⁷ 7s²",
    "oxidation": "+9",
    "electronegativity": "N/A",
    "radius": "N/A",
    "ionization": "N/A",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "1982",
    "image": "https://images-of-elements.com/meitnerium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Meitnerium"
  },
  "Ds": {
    "name": "Darmstadtium",
    "number": 110,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "281 u",
    "config": "[Rn] 5f¹⁴ 6d⁸ 7s²",
    "oxidation": "0, +2, +4, +6",
    "electronegativity": "N/A",
    "radius": "N/A",
    "ionization": "N/A",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "1994",
    "image": "https://images-of-elements.com/darmstadtium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Darmstadtium"
  },
  "Rg": {
    "name": "Roentgenium",
    "number": 111,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "280 u",
    "config": "[Rn] 5f¹⁴ 6d⁹ 7s²",
    "oxidation": "+1, +3, +5",
    "electronegativity": "N/A",
    "radius": "N/A",
    "ionization": "N/A",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "1994",
    "image": "https://images-of-elements.com/roentgenium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Roentgenium"
  },
  "Cn": {
    "name": "Copernicium",
    "number": 112,
    "type": "Transition Metal",
    "state": "Solid",
    "mass": "285 u",
    "config": "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
    "oxidation": "0, +1, +2, +4",
    "electronegativity": "N/A",
    "radius": "N/A",
    "ionization": "N/A",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "1996",
    "image": "https://images-of-elements.com/copernicium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Copernicium"
  },
  "Nh": {
    "name": "Nihonium",
    "number": 113,
    "type": "Post-transition Metal",
    "state": "Solid",
    "mass": "286 u",
    "config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
    "oxidation": "+1, +3, +5",
    "electronegativity": "N/A",
    "radius": "N/A",
    "ionization": "N/A",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "2003",
    "image": "https://images-of-elements.com/nihonium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Nihonium"
  },
  "Fl": {
    "name": "Flerovium",
    "number": 114,
    "type": "Post-transition Metal",
    "state": "Solid",
    "mass": "289 u",
    "config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
    "oxidation": "0, +1, +2, +4",
    "electronegativity": "N/A",
    "radius": "N/A",
    "ionization": "N/A",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "1998",
    "image": "https://images-of-elements.com/flerovium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Flerovium"
  },
  "Mc": {
    "name": "Moscovium",
    "number": 115,
    "type": "Post-transition Metal",
    "state": "Solid",
    "mass": "290 u",
    "config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
    "oxidation": "+1, +3, +5",
    "electronegativity": "N/A",
    "radius": "N/A",
    "ionization": "N/A",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "2003",
    "image": "https://images-of-elements.com/moscovium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Moscovium"
  },
  "Lv": {
    "name": "Livermorium",
    "number": 116,
    "type": "Post-transition Metal",
    "state": "Solid",
    "mass": "293 u",
    "config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
    "oxidation": "+2, +4",
    "electronegativity": "N/A",
    "radius": "N/A",
    "ionization": "N/A",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "2000",
    "image": "https://images-of-elements.com/livermorium.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Livermorium"
  },
  "Ts": {
    "name": "Tennessine",
    "number": 117,
    "type": "Halogen",
    "state": "Solid",
    "mass": "294 u",
    "config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
    "oxidation": "-1, +1, +3, +5, +7",
    "electronegativity": "N/A",
    "radius": "N/A",
    "ionization": "N/A",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "2010",
    "image": "https://images-of-elements.com/tennessine.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Tennessine"
  },
  "Og": {
    "name": "Oganesson",
    "number": 118,
    "type": "Noble Gas",
    "state": "Solid",
    "mass": "294 u",
    "config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
    "oxidation": "0, +2, +4",
    "electronegativity": "N/A",
    "radius": "N/A",
    "ionization": "N/A",
    "affinity": "N/A",
    "melting": "N/A",
    "boiling": "N/A",
    "density": "N/A",
    "discovered": "2002",
    "image": "https://images-of-elements.com/oganesson.jpg",
    "wiki": "https://en.wikipedia.org/wiki/Oganesson"
  }
}
